services:
  timeserver1:
    container_name: timeserver1
    build:
      dockerfile: Dockerfile.timeserver
      context: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SERVER_ID=server1
      - REGION_ID=local
    command: ["/app/server", "-id", "server1", "-region", "local", "-address", ":8080"]

  timeserver2:
    container_name: timeserver2
    build:
      dockerfile: Dockerfile.timeserver
      context: .
    restart: always
    ports:
      - "8081:8080"
    environment:
      - SERVER_ID=server2
      - REGION_ID=local
    command: ["/app/server", "-id", "server2", "-region", "local", "-address", ":8080"]

volumes:
  devnet_db: