FROM golang:1.22-alpine

WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy source code
COPY . .

# Build the time server
RUN cd cmd/timeserver && CGO_ENABLED=0 GOOS=linux go build -o /app/server

# Expose the default port
EXPOSE 8080

# Run the server
CMD ["/app/server"]
