# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import region_service_pb2 as region__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in region_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RegionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRegion = channel.unary_unary(
                '/teeregion.RegionService/CreateRegion',
                request_serializer=region__service__pb2.CreateRegionRequest.SerializeToString,
                response_deserializer=region__service__pb2.CreateRegionResponse.FromString,
                _registered_method=True)
        self.UpdateRegion = channel.unary_unary(
                '/teeregion.RegionService/UpdateRegion',
                request_serializer=region__service__pb2.UpdateRegionRequest.SerializeToString,
                response_deserializer=region__service__pb2.UpdateRegionResponse.FromString,
                _registered_method=True)
        self.DeleteRegion = channel.unary_unary(
                '/teeregion.RegionService/DeleteRegion',
                request_serializer=region__service__pb2.DeleteRegionRequest.SerializeToString,
                response_deserializer=region__service__pb2.DeleteRegionResponse.FromString,
                _registered_method=True)
        self.GetRegionStatus = channel.unary_unary(
                '/teeregion.RegionService/GetRegionStatus',
                request_serializer=region__service__pb2.GetRegionStatusRequest.SerializeToString,
                response_deserializer=region__service__pb2.GetRegionStatusResponse.FromString,
                _registered_method=True)
        self.ListRegions = channel.unary_unary(
                '/teeregion.RegionService/ListRegions',
                request_serializer=region__service__pb2.ListRegionsRequest.SerializeToString,
                response_deserializer=region__service__pb2.ListRegionsResponse.FromString,
                _registered_method=True)


class RegionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateRegion(self, request, context):
        """Create/update/delete regions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRegion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRegion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRegionStatus(self, request, context):
        """Region status/health
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRegions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRegion': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRegion,
                    request_deserializer=region__service__pb2.CreateRegionRequest.FromString,
                    response_serializer=region__service__pb2.CreateRegionResponse.SerializeToString,
            ),
            'UpdateRegion': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRegion,
                    request_deserializer=region__service__pb2.UpdateRegionRequest.FromString,
                    response_serializer=region__service__pb2.UpdateRegionResponse.SerializeToString,
            ),
            'DeleteRegion': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRegion,
                    request_deserializer=region__service__pb2.DeleteRegionRequest.FromString,
                    response_serializer=region__service__pb2.DeleteRegionResponse.SerializeToString,
            ),
            'GetRegionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRegionStatus,
                    request_deserializer=region__service__pb2.GetRegionStatusRequest.FromString,
                    response_serializer=region__service__pb2.GetRegionStatusResponse.SerializeToString,
            ),
            'ListRegions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRegions,
                    request_deserializer=region__service__pb2.ListRegionsRequest.FromString,
                    response_serializer=region__service__pb2.ListRegionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'teeregion.RegionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('teeregion.RegionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RegionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateRegion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/teeregion.RegionService/CreateRegion',
            region__service__pb2.CreateRegionRequest.SerializeToString,
            region__service__pb2.CreateRegionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRegion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/teeregion.RegionService/UpdateRegion',
            region__service__pb2.UpdateRegionRequest.SerializeToString,
            region__service__pb2.UpdateRegionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRegion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/teeregion.RegionService/DeleteRegion',
            region__service__pb2.DeleteRegionRequest.SerializeToString,
            region__service__pb2.DeleteRegionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRegionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/teeregion.RegionService/GetRegionStatus',
            region__service__pb2.GetRegionStatusRequest.SerializeToString,
            region__service__pb2.GetRegionStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRegions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/teeregion.RegionService/ListRegions',
            region__service__pb2.ListRegionsRequest.SerializeToString,
            region__service__pb2.ListRegionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
