# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: region_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'region_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14region_service.proto\x12\tteeregion\"L\n\x0cRegionMetric\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x0c\n\x04unit\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"v\n\tTEERegion\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07tee_ids\x18\x02 \x03(\x0c\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\t\x12(\n\x07metrics\x18\x05 \x03(\x0b\x32\x17.teeregion.RegionMetric\"2\n\x13\x43reateRegionRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07tee_ids\x18\x02 \x03(\x0c\"<\n\x14\x43reateRegionResponse\x12$\n\x06region\x18\x01 \x01(\x0b\x32\x14.teeregion.TEERegion\"B\n\x13UpdateRegionRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07tee_ids\x18\x02 \x03(\x0c\x12\x0e\n\x06status\x18\x03 \x01(\t\"<\n\x14UpdateRegionResponse\x12$\n\x06region\x18\x01 \x01(\x0b\x32\x14.teeregion.TEERegion\"!\n\x13\x44\x65leteRegionRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\'\n\x14\x44\x65leteRegionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"$\n\x16GetRegionStatusRequest\x12\n\n\x02id\x18\x01 \x01(\t\"_\n\x17GetRegionStatusResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12(\n\x07metrics\x18\x03 \x03(\x0b\x32\x17.teeregion.RegionMetric\"\x14\n\x12ListRegionsRequest\"<\n\x13ListRegionsResponse\x12%\n\x07regions\x18\x01 \x03(\x0b\x32\x14.teeregion.TEERegion2\xaa\x03\n\rRegionService\x12O\n\x0c\x43reateRegion\x12\x1e.teeregion.CreateRegionRequest\x1a\x1f.teeregion.CreateRegionResponse\x12O\n\x0cUpdateRegion\x12\x1e.teeregion.UpdateRegionRequest\x1a\x1f.teeregion.UpdateRegionResponse\x12O\n\x0c\x44\x65leteRegion\x12\x1e.teeregion.DeleteRegionRequest\x1a\x1f.teeregion.DeleteRegionResponse\x12X\n\x0fGetRegionStatus\x12!.teeregion.GetRegionStatusRequest\x1a\".teeregion.GetRegionStatusResponse\x12L\n\x0bListRegions\x12\x1d.teeregion.ListRegionsRequest\x1a\x1e.teeregion.ListRegionsResponseB&Z$github.com/rhombus-tech/vm/tee/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'region_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/rhombus-tech/vm/tee/proto'
  _globals['_REGIONMETRIC']._serialized_start=35
  _globals['_REGIONMETRIC']._serialized_end=111
  _globals['_TEEREGION']._serialized_start=113
  _globals['_TEEREGION']._serialized_end=231
  _globals['_CREATEREGIONREQUEST']._serialized_start=233
  _globals['_CREATEREGIONREQUEST']._serialized_end=283
  _globals['_CREATEREGIONRESPONSE']._serialized_start=285
  _globals['_CREATEREGIONRESPONSE']._serialized_end=345
  _globals['_UPDATEREGIONREQUEST']._serialized_start=347
  _globals['_UPDATEREGIONREQUEST']._serialized_end=413
  _globals['_UPDATEREGIONRESPONSE']._serialized_start=415
  _globals['_UPDATEREGIONRESPONSE']._serialized_end=475
  _globals['_DELETEREGIONREQUEST']._serialized_start=477
  _globals['_DELETEREGIONREQUEST']._serialized_end=510
  _globals['_DELETEREGIONRESPONSE']._serialized_start=512
  _globals['_DELETEREGIONRESPONSE']._serialized_end=551
  _globals['_GETREGIONSTATUSREQUEST']._serialized_start=553
  _globals['_GETREGIONSTATUSREQUEST']._serialized_end=589
  _globals['_GETREGIONSTATUSRESPONSE']._serialized_start=591
  _globals['_GETREGIONSTATUSRESPONSE']._serialized_end=686
  _globals['_LISTREGIONSREQUEST']._serialized_start=688
  _globals['_LISTREGIONSREQUEST']._serialized_end=708
  _globals['_LISTREGIONSRESPONSE']._serialized_start=710
  _globals['_LISTREGIONSRESPONSE']._serialized_end=770
  _globals['_REGIONSERVICE']._serialized_start=773
  _globals['_REGIONSERVICE']._serialized_end=1199
# @@protoc_insertion_point(module_scope)
