# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tee_service_pb2 as tee__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tee_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TeeExecutionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/proto.TeeExecution/Execute',
                request_serializer=tee__service__pb2.ExecutionRequest.SerializeToString,
                response_deserializer=tee__service__pb2.ExecutionResult.FromString,
                _registered_method=True)
        self.GetRegions = channel.unary_unary(
                '/proto.TeeExecution/GetRegions',
                request_serializer=tee__service__pb2.GetRegionsRequest.SerializeToString,
                response_deserializer=tee__service__pb2.GetRegionsResponse.FromString,
                _registered_method=True)
        self.GetAttestations = channel.unary_unary(
                '/proto.TeeExecution/GetAttestations',
                request_serializer=tee__service__pb2.GetAttestationsRequest.SerializeToString,
                response_deserializer=tee__service__pb2.RegionAttestations.FromString,
                _registered_method=True)
        self.DeployContract = channel.unary_unary(
                '/proto.TeeExecution/DeployContract',
                request_serializer=tee__service__pb2.DeployContractRequest.SerializeToString,
                response_deserializer=tee__service__pb2.DeployContractResponse.FromString,
                _registered_method=True)
        self.GetEvent = channel.unary_unary(
                '/proto.TeeExecution/GetEvent',
                request_serializer=tee__service__pb2.GetEventRequest.SerializeToString,
                response_deserializer=tee__service__pb2.GetEventResponse.FromString,
                _registered_method=True)
        self.SetupTestObject = channel.unary_unary(
                '/proto.TeeExecution/SetupTestObject',
                request_serializer=tee__service__pb2.SetupTestObjectRequest.SerializeToString,
                response_deserializer=tee__service__pb2.SetupTestObjectResponse.FromString,
                _registered_method=True)
        self.CallContract = channel.unary_unary(
                '/proto.TeeExecution/CallContract',
                request_serializer=tee__service__pb2.CallContractRequest.SerializeToString,
                response_deserializer=tee__service__pb2.CallContractResponse.FromString,
                _registered_method=True)


class TeeExecutionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRegions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAttestations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeployContract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetupTestObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallContract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TeeExecutionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=tee__service__pb2.ExecutionRequest.FromString,
                    response_serializer=tee__service__pb2.ExecutionResult.SerializeToString,
            ),
            'GetRegions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRegions,
                    request_deserializer=tee__service__pb2.GetRegionsRequest.FromString,
                    response_serializer=tee__service__pb2.GetRegionsResponse.SerializeToString,
            ),
            'GetAttestations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAttestations,
                    request_deserializer=tee__service__pb2.GetAttestationsRequest.FromString,
                    response_serializer=tee__service__pb2.RegionAttestations.SerializeToString,
            ),
            'DeployContract': grpc.unary_unary_rpc_method_handler(
                    servicer.DeployContract,
                    request_deserializer=tee__service__pb2.DeployContractRequest.FromString,
                    response_serializer=tee__service__pb2.DeployContractResponse.SerializeToString,
            ),
            'GetEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvent,
                    request_deserializer=tee__service__pb2.GetEventRequest.FromString,
                    response_serializer=tee__service__pb2.GetEventResponse.SerializeToString,
            ),
            'SetupTestObject': grpc.unary_unary_rpc_method_handler(
                    servicer.SetupTestObject,
                    request_deserializer=tee__service__pb2.SetupTestObjectRequest.FromString,
                    response_serializer=tee__service__pb2.SetupTestObjectResponse.SerializeToString,
            ),
            'CallContract': grpc.unary_unary_rpc_method_handler(
                    servicer.CallContract,
                    request_deserializer=tee__service__pb2.CallContractRequest.FromString,
                    response_serializer=tee__service__pb2.CallContractResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.TeeExecution', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.TeeExecution', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TeeExecution(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.TeeExecution/Execute',
            tee__service__pb2.ExecutionRequest.SerializeToString,
            tee__service__pb2.ExecutionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRegions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.TeeExecution/GetRegions',
            tee__service__pb2.GetRegionsRequest.SerializeToString,
            tee__service__pb2.GetRegionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAttestations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.TeeExecution/GetAttestations',
            tee__service__pb2.GetAttestationsRequest.SerializeToString,
            tee__service__pb2.RegionAttestations.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeployContract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.TeeExecution/DeployContract',
            tee__service__pb2.DeployContractRequest.SerializeToString,
            tee__service__pb2.DeployContractResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.TeeExecution/GetEvent',
            tee__service__pb2.GetEventRequest.SerializeToString,
            tee__service__pb2.GetEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetupTestObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.TeeExecution/SetupTestObject',
            tee__service__pb2.SetupTestObjectRequest.SerializeToString,
            tee__service__pb2.SetupTestObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallContract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.TeeExecution/CallContract',
            tee__service__pb2.CallContractRequest.SerializeToString,
            tee__service__pb2.CallContractResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
