# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tee_mesh_pb2 as tee__mesh__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tee_mesh_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TeeMeshStub(object):
    """TeeMesh service manages direct communication between TEEs
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Discover = channel.unary_unary(
                '/proto.TeeMesh/Discover',
                request_serializer=tee__mesh__pb2.DiscoveryRequest.SerializeToString,
                response_deserializer=tee__mesh__pb2.DiscoveryResponse.FromString,
                _registered_method=True)
        self.DirectExecute = channel.unary_unary(
                '/proto.TeeMesh/DirectExecute',
                request_serializer=tee__mesh__pb2.DirectExecutionRequest.SerializeToString,
                response_deserializer=tee__mesh__pb2.DirectExecutionResponse.FromString,
                _registered_method=True)
        self.ProxyExecute = channel.unary_unary(
                '/proto.TeeMesh/ProxyExecute',
                request_serializer=tee__mesh__pb2.ProxyExecutionRequest.SerializeToString,
                response_deserializer=tee__mesh__pb2.DirectExecutionResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/proto.TeeMesh/Ping',
                request_serializer=tee__mesh__pb2.PingRequest.SerializeToString,
                response_deserializer=tee__mesh__pb2.PingResponse.FromString,
                _registered_method=True)
        self.Sync = channel.unary_unary(
                '/proto.TeeMesh/Sync',
                request_serializer=tee__mesh__pb2.SyncRequest.SerializeToString,
                response_deserializer=tee__mesh__pb2.SyncResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/proto.TeeMesh/Heartbeat',
                request_serializer=tee__mesh__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=tee__mesh__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.GetPeers = channel.unary_unary(
                '/proto.TeeMesh/GetPeers',
                request_serializer=tee__mesh__pb2.GetPeersRequest.SerializeToString,
                response_deserializer=tee__mesh__pb2.GetPeersResponse.FromString,
                _registered_method=True)


class TeeMeshServicer(object):
    """TeeMesh service manages direct communication between TEEs
    """

    def Discover(self, request, context):
        """Discover allows TEEs to find each other within the same region
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DirectExecute(self, request, context):
        """DirectExecute allows one TEE to directly execute operations on another
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProxyExecute(self, request, context):
        """ProxyExecute allows execution with automatic failover between TEEs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Ping is a simple health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sync(self, request, context):
        """Sync syncs state between TEEs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Heartbeat sends and receives TEE attestation and status updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPeers(self, request, context):
        """GetPeers retrieves a list of attested peers in the region
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TeeMeshServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Discover': grpc.unary_unary_rpc_method_handler(
                    servicer.Discover,
                    request_deserializer=tee__mesh__pb2.DiscoveryRequest.FromString,
                    response_serializer=tee__mesh__pb2.DiscoveryResponse.SerializeToString,
            ),
            'DirectExecute': grpc.unary_unary_rpc_method_handler(
                    servicer.DirectExecute,
                    request_deserializer=tee__mesh__pb2.DirectExecutionRequest.FromString,
                    response_serializer=tee__mesh__pb2.DirectExecutionResponse.SerializeToString,
            ),
            'ProxyExecute': grpc.unary_unary_rpc_method_handler(
                    servicer.ProxyExecute,
                    request_deserializer=tee__mesh__pb2.ProxyExecutionRequest.FromString,
                    response_serializer=tee__mesh__pb2.DirectExecutionResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=tee__mesh__pb2.PingRequest.FromString,
                    response_serializer=tee__mesh__pb2.PingResponse.SerializeToString,
            ),
            'Sync': grpc.unary_unary_rpc_method_handler(
                    servicer.Sync,
                    request_deserializer=tee__mesh__pb2.SyncRequest.FromString,
                    response_serializer=tee__mesh__pb2.SyncResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=tee__mesh__pb2.HeartbeatRequest.FromString,
                    response_serializer=tee__mesh__pb2.HeartbeatResponse.SerializeToString,
            ),
            'GetPeers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPeers,
                    request_deserializer=tee__mesh__pb2.GetPeersRequest.FromString,
                    response_serializer=tee__mesh__pb2.GetPeersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.TeeMesh', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.TeeMesh', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TeeMesh(object):
    """TeeMesh service manages direct communication between TEEs
    """

    @staticmethod
    def Discover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.TeeMesh/Discover',
            tee__mesh__pb2.DiscoveryRequest.SerializeToString,
            tee__mesh__pb2.DiscoveryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DirectExecute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.TeeMesh/DirectExecute',
            tee__mesh__pb2.DirectExecutionRequest.SerializeToString,
            tee__mesh__pb2.DirectExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProxyExecute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.TeeMesh/ProxyExecute',
            tee__mesh__pb2.ProxyExecutionRequest.SerializeToString,
            tee__mesh__pb2.DirectExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.TeeMesh/Ping',
            tee__mesh__pb2.PingRequest.SerializeToString,
            tee__mesh__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.TeeMesh/Sync',
            tee__mesh__pb2.SyncRequest.SerializeToString,
            tee__mesh__pb2.SyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.TeeMesh/Heartbeat',
            tee__mesh__pb2.HeartbeatRequest.SerializeToString,
            tee__mesh__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPeers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.TeeMesh/GetPeers',
            tee__mesh__pb2.GetPeersRequest.SerializeToString,
            tee__mesh__pb2.GetPeersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
