// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.2
// source: region_federation.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RegionFederation_DiscoverRegions_FullMethodName         = "/proto.RegionFederation/DiscoverRegions"
	RegionFederation_SynchronizeState_FullMethodName        = "/proto.RegionFederation/SynchronizeState"
	RegionFederation_ProposeStateChange_FullMethodName      = "/proto.RegionFederation/ProposeStateChange"
	RegionFederation_CreateFederatedSnapshot_FullMethodName = "/proto.RegionFederation/CreateFederatedSnapshot"
	RegionFederation_VerifyFederatedSnapshot_FullMethodName = "/proto.RegionFederation/VerifyFederatedSnapshot"
	RegionFederation_QueryRegionState_FullMethodName        = "/proto.RegionFederation/QueryRegionState"
	RegionFederation_RequestConsensus_FullMethodName        = "/proto.RegionFederation/RequestConsensus"
	RegionFederation_HeartbeatCheck_FullMethodName          = "/proto.RegionFederation/HeartbeatCheck"
)

// RegionFederationClient is the client API for RegionFederation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RegionFederation service defines the interface for cross-region communication
type RegionFederationClient interface {
	// DiscoverRegions discovers other regions in the federation
	DiscoverRegions(ctx context.Context, in *RegionDiscoveryRequest, opts ...grpc.CallOption) (*RegionDiscoveryResponse, error)
	// SynchronizeState synchronizes state for an object across regions
	SynchronizeState(ctx context.Context, in *RegionSyncRequest, opts ...grpc.CallOption) (*RegionSyncResponse, error)
	// ProposeStateChange proposes a state change to other regions
	ProposeStateChange(ctx context.Context, in *StateChangeProposal, opts ...grpc.CallOption) (*StateChangeResponse, error)
	// CreateFederatedSnapshot initiates creation of a federated snapshot
	CreateFederatedSnapshot(ctx context.Context, in *FederatedSnapshotRequest, opts ...grpc.CallOption) (*FederatedSnapshotResponse, error)
	// VerifyFederatedSnapshot verifies a federated snapshot
	VerifyFederatedSnapshot(ctx context.Context, in *VerifyFederatedSnapshotRequest, opts ...grpc.CallOption) (*VerifyFederatedSnapshotResponse, error)
	// QueryRegionState queries the state of an object in another region
	QueryRegionState(ctx context.Context, in *RegionStateQuery, opts ...grpc.CallOption) (*RegionStateResponse, error)
	// RequestConsensus requests consensus from other regions on a proposed value
	RequestConsensus(ctx context.Context, in *ConsensusRequest, opts ...grpc.CallOption) (*ConsensusResponse, error)
	// HeartbeatCheck verifies that a region is still available
	HeartbeatCheck(ctx context.Context, in *RegionHeartbeatRequest, opts ...grpc.CallOption) (*RegionHeartbeatResponse, error)
}

type regionFederationClient struct {
	cc grpc.ClientConnInterface
}

func NewRegionFederationClient(cc grpc.ClientConnInterface) RegionFederationClient {
	return &regionFederationClient{cc}
}

func (c *regionFederationClient) DiscoverRegions(ctx context.Context, in *RegionDiscoveryRequest, opts ...grpc.CallOption) (*RegionDiscoveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegionDiscoveryResponse)
	err := c.cc.Invoke(ctx, RegionFederation_DiscoverRegions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regionFederationClient) SynchronizeState(ctx context.Context, in *RegionSyncRequest, opts ...grpc.CallOption) (*RegionSyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegionSyncResponse)
	err := c.cc.Invoke(ctx, RegionFederation_SynchronizeState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regionFederationClient) ProposeStateChange(ctx context.Context, in *StateChangeProposal, opts ...grpc.CallOption) (*StateChangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StateChangeResponse)
	err := c.cc.Invoke(ctx, RegionFederation_ProposeStateChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regionFederationClient) CreateFederatedSnapshot(ctx context.Context, in *FederatedSnapshotRequest, opts ...grpc.CallOption) (*FederatedSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FederatedSnapshotResponse)
	err := c.cc.Invoke(ctx, RegionFederation_CreateFederatedSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regionFederationClient) VerifyFederatedSnapshot(ctx context.Context, in *VerifyFederatedSnapshotRequest, opts ...grpc.CallOption) (*VerifyFederatedSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyFederatedSnapshotResponse)
	err := c.cc.Invoke(ctx, RegionFederation_VerifyFederatedSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regionFederationClient) QueryRegionState(ctx context.Context, in *RegionStateQuery, opts ...grpc.CallOption) (*RegionStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegionStateResponse)
	err := c.cc.Invoke(ctx, RegionFederation_QueryRegionState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regionFederationClient) RequestConsensus(ctx context.Context, in *ConsensusRequest, opts ...grpc.CallOption) (*ConsensusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsensusResponse)
	err := c.cc.Invoke(ctx, RegionFederation_RequestConsensus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regionFederationClient) HeartbeatCheck(ctx context.Context, in *RegionHeartbeatRequest, opts ...grpc.CallOption) (*RegionHeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegionHeartbeatResponse)
	err := c.cc.Invoke(ctx, RegionFederation_HeartbeatCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegionFederationServer is the server API for RegionFederation service.
// All implementations must embed UnimplementedRegionFederationServer
// for forward compatibility.
//
// RegionFederation service defines the interface for cross-region communication
type RegionFederationServer interface {
	// DiscoverRegions discovers other regions in the federation
	DiscoverRegions(context.Context, *RegionDiscoveryRequest) (*RegionDiscoveryResponse, error)
	// SynchronizeState synchronizes state for an object across regions
	SynchronizeState(context.Context, *RegionSyncRequest) (*RegionSyncResponse, error)
	// ProposeStateChange proposes a state change to other regions
	ProposeStateChange(context.Context, *StateChangeProposal) (*StateChangeResponse, error)
	// CreateFederatedSnapshot initiates creation of a federated snapshot
	CreateFederatedSnapshot(context.Context, *FederatedSnapshotRequest) (*FederatedSnapshotResponse, error)
	// VerifyFederatedSnapshot verifies a federated snapshot
	VerifyFederatedSnapshot(context.Context, *VerifyFederatedSnapshotRequest) (*VerifyFederatedSnapshotResponse, error)
	// QueryRegionState queries the state of an object in another region
	QueryRegionState(context.Context, *RegionStateQuery) (*RegionStateResponse, error)
	// RequestConsensus requests consensus from other regions on a proposed value
	RequestConsensus(context.Context, *ConsensusRequest) (*ConsensusResponse, error)
	// HeartbeatCheck verifies that a region is still available
	HeartbeatCheck(context.Context, *RegionHeartbeatRequest) (*RegionHeartbeatResponse, error)
	mustEmbedUnimplementedRegionFederationServer()
}

// UnimplementedRegionFederationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegionFederationServer struct{}

func (UnimplementedRegionFederationServer) DiscoverRegions(context.Context, *RegionDiscoveryRequest) (*RegionDiscoveryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiscoverRegions not implemented")
}
func (UnimplementedRegionFederationServer) SynchronizeState(context.Context, *RegionSyncRequest) (*RegionSyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SynchronizeState not implemented")
}
func (UnimplementedRegionFederationServer) ProposeStateChange(context.Context, *StateChangeProposal) (*StateChangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProposeStateChange not implemented")
}
func (UnimplementedRegionFederationServer) CreateFederatedSnapshot(context.Context, *FederatedSnapshotRequest) (*FederatedSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFederatedSnapshot not implemented")
}
func (UnimplementedRegionFederationServer) VerifyFederatedSnapshot(context.Context, *VerifyFederatedSnapshotRequest) (*VerifyFederatedSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyFederatedSnapshot not implemented")
}
func (UnimplementedRegionFederationServer) QueryRegionState(context.Context, *RegionStateQuery) (*RegionStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryRegionState not implemented")
}
func (UnimplementedRegionFederationServer) RequestConsensus(context.Context, *ConsensusRequest) (*ConsensusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestConsensus not implemented")
}
func (UnimplementedRegionFederationServer) HeartbeatCheck(context.Context, *RegionHeartbeatRequest) (*RegionHeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeartbeatCheck not implemented")
}
func (UnimplementedRegionFederationServer) mustEmbedUnimplementedRegionFederationServer() {}
func (UnimplementedRegionFederationServer) testEmbeddedByValue()                          {}

// UnsafeRegionFederationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegionFederationServer will
// result in compilation errors.
type UnsafeRegionFederationServer interface {
	mustEmbedUnimplementedRegionFederationServer()
}

func RegisterRegionFederationServer(s grpc.ServiceRegistrar, srv RegionFederationServer) {
	// If the following call pancis, it indicates UnimplementedRegionFederationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RegionFederation_ServiceDesc, srv)
}

func _RegionFederation_DiscoverRegions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegionDiscoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionFederationServer).DiscoverRegions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegionFederation_DiscoverRegions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionFederationServer).DiscoverRegions(ctx, req.(*RegionDiscoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegionFederation_SynchronizeState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegionSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionFederationServer).SynchronizeState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegionFederation_SynchronizeState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionFederationServer).SynchronizeState(ctx, req.(*RegionSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegionFederation_ProposeStateChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateChangeProposal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionFederationServer).ProposeStateChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegionFederation_ProposeStateChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionFederationServer).ProposeStateChange(ctx, req.(*StateChangeProposal))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegionFederation_CreateFederatedSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FederatedSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionFederationServer).CreateFederatedSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegionFederation_CreateFederatedSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionFederationServer).CreateFederatedSnapshot(ctx, req.(*FederatedSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegionFederation_VerifyFederatedSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyFederatedSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionFederationServer).VerifyFederatedSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegionFederation_VerifyFederatedSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionFederationServer).VerifyFederatedSnapshot(ctx, req.(*VerifyFederatedSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegionFederation_QueryRegionState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegionStateQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionFederationServer).QueryRegionState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegionFederation_QueryRegionState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionFederationServer).QueryRegionState(ctx, req.(*RegionStateQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegionFederation_RequestConsensus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsensusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionFederationServer).RequestConsensus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegionFederation_RequestConsensus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionFederationServer).RequestConsensus(ctx, req.(*ConsensusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegionFederation_HeartbeatCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegionHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionFederationServer).HeartbeatCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegionFederation_HeartbeatCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionFederationServer).HeartbeatCheck(ctx, req.(*RegionHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegionFederation_ServiceDesc is the grpc.ServiceDesc for RegionFederation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegionFederation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RegionFederation",
	HandlerType: (*RegionFederationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DiscoverRegions",
			Handler:    _RegionFederation_DiscoverRegions_Handler,
		},
		{
			MethodName: "SynchronizeState",
			Handler:    _RegionFederation_SynchronizeState_Handler,
		},
		{
			MethodName: "ProposeStateChange",
			Handler:    _RegionFederation_ProposeStateChange_Handler,
		},
		{
			MethodName: "CreateFederatedSnapshot",
			Handler:    _RegionFederation_CreateFederatedSnapshot_Handler,
		},
		{
			MethodName: "VerifyFederatedSnapshot",
			Handler:    _RegionFederation_VerifyFederatedSnapshot_Handler,
		},
		{
			MethodName: "QueryRegionState",
			Handler:    _RegionFederation_QueryRegionState_Handler,
		},
		{
			MethodName: "RequestConsensus",
			Handler:    _RegionFederation_RequestConsensus_Handler,
		},
		{
			MethodName: "HeartbeatCheck",
			Handler:    _RegionFederation_HeartbeatCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "region_federation.proto",
}
