// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.2
// source: region_federation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncMode defines the mode of synchronization
type SyncMode int32

const (
	SyncMode_PUSH          SyncMode = 0 // Push state to target
	SyncMode_PULL          SyncMode = 1 // Pull state from target
	SyncMode_BIDIRECTIONAL SyncMode = 2 // Synchronize in both directions
)

// Enum value maps for SyncMode.
var (
	SyncMode_name = map[int32]string{
		0: "PUSH",
		1: "PULL",
		2: "BIDIRECTIONAL",
	}
	SyncMode_value = map[string]int32{
		"PUSH":          0,
		"PULL":          1,
		"BIDIRECTIONAL": 2,
	}
)

func (x SyncMode) Enum() *SyncMode {
	p := new(SyncMode)
	*p = x
	return p
}

func (x SyncMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncMode) Descriptor() protoreflect.EnumDescriptor {
	return file_region_federation_proto_enumTypes[0].Descriptor()
}

func (SyncMode) Type() protoreflect.EnumType {
	return &file_region_federation_proto_enumTypes[0]
}

func (x SyncMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncMode.Descriptor instead.
func (SyncMode) EnumDescriptor() ([]byte, []int) {
	return file_region_federation_proto_rawDescGZIP(), []int{0}
}

// RegionDiscoveryRequest is used to discover other regions
type RegionDiscoveryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FederationId   string                 `protobuf:"bytes,1,opt,name=federation_id,json=federationId,proto3" json:"federation_id,omitempty"`
	SourceRegionId string                 `protobuf:"bytes,2,opt,name=source_region_id,json=sourceRegionId,proto3" json:"source_region_id,omitempty"`
	RegionType     string                 `protobuf:"bytes,3,opt,name=region_type,json=regionType,proto3" json:"region_type,omitempty"` // e.g., "primary", "secondary", "backup"
	Capabilities   []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	ApiVersion     string                 `protobuf:"bytes,5,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Signature      []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"` // Signature for authentication
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegionDiscoveryRequest) Reset() {
	*x = RegionDiscoveryRequest{}
	mi := &file_region_federation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionDiscoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionDiscoveryRequest) ProtoMessage() {}

func (x *RegionDiscoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_region_federation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionDiscoveryRequest.ProtoReflect.Descriptor instead.
func (*RegionDiscoveryRequest) Descriptor() ([]byte, []int) {
	return file_region_federation_proto_rawDescGZIP(), []int{0}
}

func (x *RegionDiscoveryRequest) GetFederationId() string {
	if x != nil {
		return x.FederationId
	}
	return ""
}

func (x *RegionDiscoveryRequest) GetSourceRegionId() string {
	if x != nil {
		return x.SourceRegionId
	}
	return ""
}

func (x *RegionDiscoveryRequest) GetRegionType() string {
	if x != nil {
		return x.RegionType
	}
	return ""
}

func (x *RegionDiscoveryRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegionDiscoveryRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *RegionDiscoveryRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// RegionDiscoveryResponse provides information about available regions
type RegionDiscoveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Regions       []*RegionInfo          `protobuf:"bytes,3,rep,name=regions,proto3" json:"regions,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"` // Signature for authentication
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionDiscoveryResponse) Reset() {
	*x = RegionDiscoveryResponse{}
	mi := &file_region_federation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionDiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionDiscoveryResponse) ProtoMessage() {}

func (x *RegionDiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_region_federation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionDiscoveryResponse.ProtoReflect.Descriptor instead.
func (*RegionDiscoveryResponse) Descriptor() ([]byte, []int) {
	return file_region_federation_proto_rawDescGZIP(), []int{1}
}

func (x *RegionDiscoveryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegionDiscoveryResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RegionDiscoveryResponse) GetRegions() []*RegionInfo {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *RegionDiscoveryResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// RegionInfo contains information about a region
type RegionInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RegionId          string                 `protobuf:"bytes,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Endpoint          string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                                             // gRPC endpoint
	Status            string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                                 // "active", "inactive", "degraded"
	AdminCapabilities bool                   `protobuf:"varint,4,opt,name=admin_capabilities,json=adminCapabilities,proto3" json:"admin_capabilities,omitempty"` // Whether this region has admin capabilities
	LastContactTime   int64                  `protobuf:"varint,5,opt,name=last_contact_time,json=lastContactTime,proto3" json:"last_contact_time,omitempty"`     // Unix timestamp of last contact
	TeeCount          int32                  `protobuf:"varint,6,opt,name=tee_count,json=teeCount,proto3" json:"tee_count,omitempty"`                            // Number of TEEs in this region
	Capabilities      []string               `protobuf:"bytes,7,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegionInfo) Reset() {
	*x = RegionInfo{}
	mi := &file_region_federation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionInfo) ProtoMessage() {}

func (x *RegionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_region_federation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionInfo.ProtoReflect.Descriptor instead.
func (*RegionInfo) Descriptor() ([]byte, []int) {
	return file_region_federation_proto_rawDescGZIP(), []int{2}
}

func (x *RegionInfo) GetRegionId() string {
	if x != nil {
		return x.RegionId
	}
	return ""
}

func (x *RegionInfo) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RegionInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegionInfo) GetAdminCapabilities() bool {
	if x != nil {
		return x.AdminCapabilities
	}
	return false
}

func (x *RegionInfo) GetLastContactTime() int64 {
	if x != nil {
		return x.LastContactTime
	}
	return 0
}

func (x *RegionInfo) GetTeeCount() int32 {
	if x != nil {
		return x.TeeCount
	}
	return 0
}

func (x *RegionInfo) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// RegionSyncRequest requests state synchronization with another region
type RegionSyncRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FederationId   string                 `protobuf:"bytes,1,opt,name=federation_id,json=federationId,proto3" json:"federation_id,omitempty"`
	SourceRegionId string                 `protobuf:"bytes,2,opt,name=source_region_id,json=sourceRegionId,proto3" json:"source_region_id,omitempty"`
	ObjectId       string                 `protobuf:"bytes,3,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	CurrentState   []byte                 `protobuf:"bytes,4,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"`          // Current state of the object
	StateVersion   int64                  `protobuf:"varint,5,opt,name=state_version,json=stateVersion,proto3" json:"state_version,omitempty"`         // Version number of the state
	SyncMode       SyncMode               `protobuf:"varint,6,opt,name=sync_mode,json=syncMode,proto3,enum=proto.SyncMode" json:"sync_mode,omitempty"` // "push", "pull", or "bidirectional"
	DeltaUpdate    []byte                 `protobuf:"bytes,7,opt,name=delta_update,json=deltaUpdate,proto3" json:"delta_update,omitempty"`             // Delta update instead of full state (optional)
	Signature      []byte                 `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`                                    // Signature for authentication
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegionSyncRequest) Reset() {
	*x = RegionSyncRequest{}
	mi := &file_region_federation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionSyncRequest) ProtoMessage() {}

func (x *RegionSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_region_federation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionSyncRequest.ProtoReflect.Descriptor instead.
func (*RegionSyncRequest) Descriptor() ([]byte, []int) {
	return file_region_federation_proto_rawDescGZIP(), []int{3}
}

func (x *RegionSyncRequest) GetFederationId() string {
	if x != nil {
		return x.FederationId
	}
	return ""
}

func (x *RegionSyncRequest) GetSourceRegionId() string {
	if x != nil {
		return x.SourceRegionId
	}
	return ""
}

func (x *RegionSyncRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *RegionSyncRequest) GetCurrentState() []byte {
	if x != nil {
		return x.CurrentState
	}
	return nil
}

func (x *RegionSyncRequest) GetStateVersion() int64 {
	if x != nil {
		return x.StateVersion
	}
	return 0
}

func (x *RegionSyncRequest) GetSyncMode() SyncMode {
	if x != nil {
		return x.SyncMode
	}
	return SyncMode_PUSH
}

func (x *RegionSyncRequest) GetDeltaUpdate() []byte {
	if x != nil {
		return x.DeltaUpdate
	}
	return nil
}

func (x *RegionSyncRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// RegionSyncResponse is returned after a sync operation
type RegionSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	UpdatedState  []byte                 `protobuf:"bytes,3,opt,name=updated_state,json=updatedState,proto3" json:"updated_state,omitempty"`  // Updated state if this is a pull or bidirectional sync
	StateVersion  int64                  `protobuf:"varint,4,opt,name=state_version,json=stateVersion,proto3" json:"state_version,omitempty"` // Version of the state
	HasConflict   bool                   `protobuf:"varint,5,opt,name=has_conflict,json=hasConflict,proto3" json:"has_conflict,omitempty"`    // Whether there was a conflict
	Signature     []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`                            // Signature for authentication
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionSyncResponse) Reset() {
	*x = RegionSyncResponse{}
	mi := &file_region_federation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionSyncResponse) ProtoMessage() {}

func (x *RegionSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_region_federation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionSyncResponse.ProtoReflect.Descriptor instead.
func (*RegionSyncResponse) Descriptor() ([]byte, []int) {
	return file_region_federation_proto_rawDescGZIP(), []int{4}
}

func (x *RegionSyncResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegionSyncResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RegionSyncResponse) GetUpdatedState() []byte {
	if x != nil {
		return x.UpdatedState
	}
	return nil
}

func (x *RegionSyncResponse) GetStateVersion() int64 {
	if x != nil {
		return x.StateVersion
	}
	return 0
}

func (x *RegionSyncResponse) GetHasConflict() bool {
	if x != nil {
		return x.HasConflict
	}
	return false
}

func (x *RegionSyncResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// StateChangeProposal proposes a state change to other regions
type StateChangeProposal struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FederationId   string                 `protobuf:"bytes,1,opt,name=federation_id,json=federationId,proto3" json:"federation_id,omitempty"`
	SourceRegionId string                 `protobuf:"bytes,2,opt,name=source_region_id,json=sourceRegionId,proto3" json:"source_region_id,omitempty"`
	ObjectId       string                 `protobuf:"bytes,3,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	NewState       []byte                 `protobuf:"bytes,4,opt,name=new_state,json=newState,proto3" json:"new_state,omitempty"`                    // Proposed new state
	StateVersion   int64                  `protobuf:"varint,5,opt,name=state_version,json=stateVersion,proto3" json:"state_version,omitempty"`       // Version number of the state
	ProposalId     int64                  `protobuf:"varint,6,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`             // Unique ID for this proposal
	ExpirationTime int64                  `protobuf:"varint,7,opt,name=expiration_time,json=expirationTime,proto3" json:"expiration_time,omitempty"` // When this proposal expires (Unix timestamp)
	Signature      []byte                 `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`                                  // Signature for authentication
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StateChangeProposal) Reset() {
	*x = StateChangeProposal{}
	mi := &file_region_federation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateChangeProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateChangeProposal) ProtoMessage() {}

func (x *StateChangeProposal) ProtoReflect() protoreflect.Message {
	mi := &file_region_federation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateChangeProposal.ProtoReflect.Descriptor instead.
func (*StateChangeProposal) Descriptor() ([]byte, []int) {
	return file_region_federation_proto_rawDescGZIP(), []int{5}
}

func (x *StateChangeProposal) GetFederationId() string {
	if x != nil {
		return x.FederationId
	}
	return ""
}

func (x *StateChangeProposal) GetSourceRegionId() string {
	if x != nil {
		return x.SourceRegionId
	}
	return ""
}

func (x *StateChangeProposal) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *StateChangeProposal) GetNewState() []byte {
	if x != nil {
		return x.NewState
	}
	return nil
}

func (x *StateChangeProposal) GetStateVersion() int64 {
	if x != nil {
		return x.StateVersion
	}
	return 0
}

func (x *StateChangeProposal) GetProposalId() int64 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *StateChangeProposal) GetExpirationTime() int64 {
	if x != nil {
		return x.ExpirationTime
	}
	return 0
}

func (x *StateChangeProposal) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// StateChangeResponse is the response to a state change proposal
type StateChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"` // Whether the proposal was accepted
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	StateVersion  int64                  `protobuf:"varint,3,opt,name=state_version,json=stateVersion,proto3" json:"state_version,omitempty"` // Current version number after the change
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`                            // Signature for authentication
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateChangeResponse) Reset() {
	*x = StateChangeResponse{}
	mi := &file_region_federation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateChangeResponse) ProtoMessage() {}

func (x *StateChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_region_federation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateChangeResponse.ProtoReflect.Descriptor instead.
func (*StateChangeResponse) Descriptor() ([]byte, []int) {
	return file_region_federation_proto_rawDescGZIP(), []int{6}
}

func (x *StateChangeResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *StateChangeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StateChangeResponse) GetStateVersion() int64 {
	if x != nil {
		return x.StateVersion
	}
	return 0
}

func (x *StateChangeResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// FederatedSnapshotRequest requests creation of a federated snapshot
type FederatedSnapshotRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FederationId   string                 `protobuf:"bytes,1,opt,name=federation_id,json=federationId,proto3" json:"federation_id,omitempty"`
	SourceRegionId string                 `protobuf:"bytes,2,opt,name=source_region_id,json=sourceRegionId,proto3" json:"source_region_id,omitempty"`
	TargetRegions  []string               `protobuf:"bytes,3,rep,name=target_regions,json=targetRegions,proto3" json:"target_regions,omitempty"`
	RequestId      int64                  `protobuf:"varint,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TimeoutMs      int64                  `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"` // Timeout in milliseconds
	Signature      []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`                   // Signature for authentication
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FederatedSnapshotRequest) Reset() {
	*x = FederatedSnapshotRequest{}
	mi := &file_region_federation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FederatedSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FederatedSnapshotRequest) ProtoMessage() {}

func (x *FederatedSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_region_federation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FederatedSnapshotRequest.ProtoReflect.Descriptor instead.
func (*FederatedSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_region_federation_proto_rawDescGZIP(), []int{7}
}

func (x *FederatedSnapshotRequest) GetFederationId() string {
	if x != nil {
		return x.FederationId
	}
	return ""
}

func (x *FederatedSnapshotRequest) GetSourceRegionId() string {
	if x != nil {
		return x.SourceRegionId
	}
	return ""
}

func (x *FederatedSnapshotRequest) GetTargetRegions() []string {
	if x != nil {
		return x.TargetRegions
	}
	return nil
}

func (x *FederatedSnapshotRequest) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *FederatedSnapshotRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *FederatedSnapshotRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// FederatedSnapshotResponse contains the federated snapshot
type FederatedSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Snapshot      *FederatedSnapshot     `protobuf:"bytes,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"` // Signature for authentication
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FederatedSnapshotResponse) Reset() {
	*x = FederatedSnapshotResponse{}
	mi := &file_region_federation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FederatedSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FederatedSnapshotResponse) ProtoMessage() {}

func (x *FederatedSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_region_federation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FederatedSnapshotResponse.ProtoReflect.Descriptor instead.
func (*FederatedSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_region_federation_proto_rawDescGZIP(), []int{8}
}

func (x *FederatedSnapshotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FederatedSnapshotResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *FederatedSnapshotResponse) GetSnapshot() *FederatedSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *FederatedSnapshotResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// FederatedSnapshot represents a snapshot across multiple regions
type FederatedSnapshot struct {
	state                protoimpl.MessageState       `protogen:"open.v1"`
	FederationId         string                       `protobuf:"bytes,1,opt,name=federation_id,json=federationId,proto3" json:"federation_id,omitempty"`
	SnapshotId           []byte                       `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	Timestamp            int64                        `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                                                                   // Unix timestamp
	RegionalSnapshots    map[string]*RegionalSnapshot `protobuf:"bytes,4,rep,name=regional_snapshots,json=regionalSnapshots,proto3" json:"regional_snapshots,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Region ID to snapshot mapping
	GlobalStateRoot      []byte                       `protobuf:"bytes,5,opt,name=global_state_root,json=globalStateRoot,proto3" json:"global_state_root,omitempty"`                                                                               // Merkle root of all state
	CoordinatorSignature []byte                       `protobuf:"bytes,6,opt,name=coordinator_signature,json=coordinatorSignature,proto3" json:"coordinator_signature,omitempty"`                                                                  // Signature of the coordinator
	ConsensusMetadata    map[string][]byte            `protobuf:"bytes,7,rep,name=consensus_metadata,json=consensusMetadata,proto3" json:"consensus_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional metadata
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *FederatedSnapshot) Reset() {
	*x = FederatedSnapshot{}
	mi := &file_region_federation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FederatedSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FederatedSnapshot) ProtoMessage() {}

func (x *FederatedSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_region_federation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FederatedSnapshot.ProtoReflect.Descriptor instead.
func (*FederatedSnapshot) Descriptor() ([]byte, []int) {
	return file_region_federation_proto_rawDescGZIP(), []int{9}
}

func (x *FederatedSnapshot) GetFederationId() string {
	if x != nil {
		return x.FederationId
	}
	return ""
}

func (x *FederatedSnapshot) GetSnapshotId() []byte {
	if x != nil {
		return x.SnapshotId
	}
	return nil
}

func (x *FederatedSnapshot) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *FederatedSnapshot) GetRegionalSnapshots() map[string]*RegionalSnapshot {
	if x != nil {
		return x.RegionalSnapshots
	}
	return nil
}

func (x *FederatedSnapshot) GetGlobalStateRoot() []byte {
	if x != nil {
		return x.GlobalStateRoot
	}
	return nil
}

func (x *FederatedSnapshot) GetCoordinatorSignature() []byte {
	if x != nil {
		return x.CoordinatorSignature
	}
	return nil
}

func (x *FederatedSnapshot) GetConsensusMetadata() map[string][]byte {
	if x != nil {
		return x.ConsensusMetadata
	}
	return nil
}

// RegionalSnapshot represents a snapshot for a region
type RegionalSnapshot struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RegionId       string                 `protobuf:"bytes,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	SnapshotId     []byte                 `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	Timestamp      int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp
	TeeSnapshotIds [][]byte               `protobuf:"bytes,4,rep,name=tee_snapshot_ids,json=teeSnapshotIds,proto3" json:"tee_snapshot_ids,omitempty"`
	Summary        *SnapshotSummary       `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegionalSnapshot) Reset() {
	*x = RegionalSnapshot{}
	mi := &file_region_federation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionalSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionalSnapshot) ProtoMessage() {}

func (x *RegionalSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_region_federation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionalSnapshot.ProtoReflect.Descriptor instead.
func (*RegionalSnapshot) Descriptor() ([]byte, []int) {
	return file_region_federation_proto_rawDescGZIP(), []int{10}
}

func (x *RegionalSnapshot) GetRegionId() string {
	if x != nil {
		return x.RegionId
	}
	return ""
}

func (x *RegionalSnapshot) GetSnapshotId() []byte {
	if x != nil {
		return x.SnapshotId
	}
	return nil
}

func (x *RegionalSnapshot) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RegionalSnapshot) GetTeeSnapshotIds() [][]byte {
	if x != nil {
		return x.TeeSnapshotIds
	}
	return nil
}

func (x *RegionalSnapshot) GetSummary() *SnapshotSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

// SnapshotSummary summarizes a snapshot
type SnapshotSummary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MerkleRoot      []byte                 `protobuf:"bytes,1,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`                                                                                            // Merkle root of all snapshot IDs
	StateRootHashes map[string][]byte      `protobuf:"bytes,2,rep,name=state_root_hashes,json=stateRootHashes,proto3" json:"state_root_hashes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // State root hashes by TEE ID
	ObjectCount     int32                  `protobuf:"varint,3,opt,name=object_count,json=objectCount,proto3" json:"object_count,omitempty"`                                                                                        // Number of distinct objects
	TotalStateSize  int64                  `protobuf:"varint,4,opt,name=total_state_size,json=totalStateSize,proto3" json:"total_state_size,omitempty"`                                                                             // Total size of all state data
	Metrics         map[string]float64     `protobuf:"bytes,5,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`                                        // Metrics about the snapshot
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SnapshotSummary) Reset() {
	*x = SnapshotSummary{}
	mi := &file_region_federation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotSummary) ProtoMessage() {}

func (x *SnapshotSummary) ProtoReflect() protoreflect.Message {
	mi := &file_region_federation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotSummary.ProtoReflect.Descriptor instead.
func (*SnapshotSummary) Descriptor() ([]byte, []int) {
	return file_region_federation_proto_rawDescGZIP(), []int{11}
}

func (x *SnapshotSummary) GetMerkleRoot() []byte {
	if x != nil {
		return x.MerkleRoot
	}
	return nil
}

func (x *SnapshotSummary) GetStateRootHashes() map[string][]byte {
	if x != nil {
		return x.StateRootHashes
	}
	return nil
}

func (x *SnapshotSummary) GetObjectCount() int32 {
	if x != nil {
		return x.ObjectCount
	}
	return 0
}

func (x *SnapshotSummary) GetTotalStateSize() int64 {
	if x != nil {
		return x.TotalStateSize
	}
	return 0
}

func (x *SnapshotSummary) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// VerifyFederatedSnapshotRequest requests verification of a federated snapshot
type VerifyFederatedSnapshotRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FederationId   string                 `protobuf:"bytes,1,opt,name=federation_id,json=federationId,proto3" json:"federation_id,omitempty"`
	SourceRegionId string                 `protobuf:"bytes,2,opt,name=source_region_id,json=sourceRegionId,proto3" json:"source_region_id,omitempty"`
	SnapshotId     []byte                 `protobuf:"bytes,3,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"` // ID of the snapshot to verify
	Signature      []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`                     // Signature for authentication
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerifyFederatedSnapshotRequest) Reset() {
	*x = VerifyFederatedSnapshotRequest{}
	mi := &file_region_federation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyFederatedSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyFederatedSnapshotRequest) ProtoMessage() {}

func (x *VerifyFederatedSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_region_federation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyFederatedSnapshotRequest.ProtoReflect.Descriptor instead.
func (*VerifyFederatedSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_region_federation_proto_rawDescGZIP(), []int{12}
}

func (x *VerifyFederatedSnapshotRequest) GetFederationId() string {
	if x != nil {
		return x.FederationId
	}
	return ""
}

func (x *VerifyFederatedSnapshotRequest) GetSourceRegionId() string {
	if x != nil {
		return x.SourceRegionId
	}
	return ""
}

func (x *VerifyFederatedSnapshotRequest) GetSnapshotId() []byte {
	if x != nil {
		return x.SnapshotId
	}
	return nil
}

func (x *VerifyFederatedSnapshotRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// VerifyFederatedSnapshotResponse contains the verification result
type VerifyFederatedSnapshotResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Valid           bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	RegionsVerified int32                  `protobuf:"varint,3,opt,name=regions_verified,json=regionsVerified,proto3" json:"regions_verified,omitempty"` // Number of regions that verified the snapshot
	Signature       []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`                                     // Signature for authentication
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VerifyFederatedSnapshotResponse) Reset() {
	*x = VerifyFederatedSnapshotResponse{}
	mi := &file_region_federation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyFederatedSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyFederatedSnapshotResponse) ProtoMessage() {}

func (x *VerifyFederatedSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_region_federation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyFederatedSnapshotResponse.ProtoReflect.Descriptor instead.
func (*VerifyFederatedSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_region_federation_proto_rawDescGZIP(), []int{13}
}

func (x *VerifyFederatedSnapshotResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyFederatedSnapshotResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *VerifyFederatedSnapshotResponse) GetRegionsVerified() int32 {
	if x != nil {
		return x.RegionsVerified
	}
	return 0
}

func (x *VerifyFederatedSnapshotResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// RegionStateQuery queries the state of an object in another region
type RegionStateQuery struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FederationId   string                 `protobuf:"bytes,1,opt,name=federation_id,json=federationId,proto3" json:"federation_id,omitempty"`
	SourceRegionId string                 `protobuf:"bytes,2,opt,name=source_region_id,json=sourceRegionId,proto3" json:"source_region_id,omitempty"`
	ObjectId       string                 `protobuf:"bytes,3,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	IncludeState   bool                   `protobuf:"varint,4,opt,name=include_state,json=includeState,proto3" json:"include_state,omitempty"` // Whether to include the actual state data
	Signature      []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`                            // Signature for authentication
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegionStateQuery) Reset() {
	*x = RegionStateQuery{}
	mi := &file_region_federation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionStateQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionStateQuery) ProtoMessage() {}

func (x *RegionStateQuery) ProtoReflect() protoreflect.Message {
	mi := &file_region_federation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionStateQuery.ProtoReflect.Descriptor instead.
func (*RegionStateQuery) Descriptor() ([]byte, []int) {
	return file_region_federation_proto_rawDescGZIP(), []int{14}
}

func (x *RegionStateQuery) GetFederationId() string {
	if x != nil {
		return x.FederationId
	}
	return ""
}

func (x *RegionStateQuery) GetSourceRegionId() string {
	if x != nil {
		return x.SourceRegionId
	}
	return ""
}

func (x *RegionStateQuery) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *RegionStateQuery) GetIncludeState() bool {
	if x != nil {
		return x.IncludeState
	}
	return false
}

func (x *RegionStateQuery) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// RegionStateResponse contains information about an object's state
type RegionStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	StateVersion  int64                  `protobuf:"varint,3,opt,name=state_version,json=stateVersion,proto3" json:"state_version,omitempty"` // Version of the state
	LastModified  int64                  `protobuf:"varint,4,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"` // Unix timestamp of last modification
	StateData     []byte                 `protobuf:"bytes,5,opt,name=state_data,json=stateData,proto3" json:"state_data,omitempty"`           // Only included if include_state was true
	Signature     []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`                            // Signature for authentication
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionStateResponse) Reset() {
	*x = RegionStateResponse{}
	mi := &file_region_federation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionStateResponse) ProtoMessage() {}

func (x *RegionStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_region_federation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionStateResponse.ProtoReflect.Descriptor instead.
func (*RegionStateResponse) Descriptor() ([]byte, []int) {
	return file_region_federation_proto_rawDescGZIP(), []int{15}
}

func (x *RegionStateResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *RegionStateResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RegionStateResponse) GetStateVersion() int64 {
	if x != nil {
		return x.StateVersion
	}
	return 0
}

func (x *RegionStateResponse) GetLastModified() int64 {
	if x != nil {
		return x.LastModified
	}
	return 0
}

func (x *RegionStateResponse) GetStateData() []byte {
	if x != nil {
		return x.StateData
	}
	return nil
}

func (x *RegionStateResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// ConsensusRequest requests consensus from other regions
type ConsensusRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FederationId    string                 `protobuf:"bytes,1,opt,name=federation_id,json=federationId,proto3" json:"federation_id,omitempty"`
	SourceRegionId  string                 `protobuf:"bytes,2,opt,name=source_region_id,json=sourceRegionId,proto3" json:"source_region_id,omitempty"`
	ObjectId        string                 `protobuf:"bytes,3,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	ProposedValue   []byte                 `protobuf:"bytes,4,opt,name=proposed_value,json=proposedValue,proto3" json:"proposed_value,omitempty"`       // Value to get consensus on
	ProposalId      int64                  `protobuf:"varint,5,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`               // Unique ID for this proposal
	ExpirationTime  int64                  `protobuf:"varint,6,opt,name=expiration_time,json=expirationTime,proto3" json:"expiration_time,omitempty"`   // When this request expires (Unix timestamp)
	ConsensusMethod string                 `protobuf:"bytes,7,opt,name=consensus_method,json=consensusMethod,proto3" json:"consensus_method,omitempty"` // Method for consensus
	Signature       []byte                 `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`                                    // Signature for authentication
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConsensusRequest) Reset() {
	*x = ConsensusRequest{}
	mi := &file_region_federation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusRequest) ProtoMessage() {}

func (x *ConsensusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_region_federation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusRequest.ProtoReflect.Descriptor instead.
func (*ConsensusRequest) Descriptor() ([]byte, []int) {
	return file_region_federation_proto_rawDescGZIP(), []int{16}
}

func (x *ConsensusRequest) GetFederationId() string {
	if x != nil {
		return x.FederationId
	}
	return ""
}

func (x *ConsensusRequest) GetSourceRegionId() string {
	if x != nil {
		return x.SourceRegionId
	}
	return ""
}

func (x *ConsensusRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *ConsensusRequest) GetProposedValue() []byte {
	if x != nil {
		return x.ProposedValue
	}
	return nil
}

func (x *ConsensusRequest) GetProposalId() int64 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *ConsensusRequest) GetExpirationTime() int64 {
	if x != nil {
		return x.ExpirationTime
	}
	return 0
}

func (x *ConsensusRequest) GetConsensusMethod() string {
	if x != nil {
		return x.ConsensusMethod
	}
	return ""
}

func (x *ConsensusRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// ConsensusResponse contains the consensus result
type ConsensusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Agreement       bool                   `protobuf:"varint,1,opt,name=agreement,proto3" json:"agreement,omitempty"` // Whether the region agrees with the proposal
	ErrorMessage    string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Reason          string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                                          // Reason for agreement/disagreement
	CounterProposal []byte                 `protobuf:"bytes,4,opt,name=counter_proposal,json=counterProposal,proto3" json:"counter_proposal,omitempty"` // Alternative value if not in agreement
	Signature       []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`                                    // Signature for authentication
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConsensusResponse) Reset() {
	*x = ConsensusResponse{}
	mi := &file_region_federation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusResponse) ProtoMessage() {}

func (x *ConsensusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_region_federation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusResponse.ProtoReflect.Descriptor instead.
func (*ConsensusResponse) Descriptor() ([]byte, []int) {
	return file_region_federation_proto_rawDescGZIP(), []int{17}
}

func (x *ConsensusResponse) GetAgreement() bool {
	if x != nil {
		return x.Agreement
	}
	return false
}

func (x *ConsensusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ConsensusResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ConsensusResponse) GetCounterProposal() []byte {
	if x != nil {
		return x.CounterProposal
	}
	return nil
}

func (x *ConsensusResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// RegionHeartbeatRequest checks if a region is still available
type RegionHeartbeatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FederationId   string                 `protobuf:"bytes,1,opt,name=federation_id,json=federationId,proto3" json:"federation_id,omitempty"`
	SourceRegionId string                 `protobuf:"bytes,2,opt,name=source_region_id,json=sourceRegionId,proto3" json:"source_region_id,omitempty"`
	Timestamp      int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp
	Signature      []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`  // Signature for authentication
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegionHeartbeatRequest) Reset() {
	*x = RegionHeartbeatRequest{}
	mi := &file_region_federation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionHeartbeatRequest) ProtoMessage() {}

func (x *RegionHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_region_federation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*RegionHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_region_federation_proto_rawDescGZIP(), []int{18}
}

func (x *RegionHeartbeatRequest) GetFederationId() string {
	if x != nil {
		return x.FederationId
	}
	return ""
}

func (x *RegionHeartbeatRequest) GetSourceRegionId() string {
	if x != nil {
		return x.SourceRegionId
	}
	return ""
}

func (x *RegionHeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RegionHeartbeatRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// RegionHeartbeatResponse confirms the region is available
type RegionHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`        // "healthy", "degraded", "maintenance"
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`  // Signature for authentication
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionHeartbeatResponse) Reset() {
	*x = RegionHeartbeatResponse{}
	mi := &file_region_federation_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionHeartbeatResponse) ProtoMessage() {}

func (x *RegionHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_region_federation_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*RegionHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_region_federation_proto_rawDescGZIP(), []int{19}
}

func (x *RegionHeartbeatResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *RegionHeartbeatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegionHeartbeatResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RegionHeartbeatResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_region_federation_proto protoreflect.FileDescriptor

const file_region_federation_proto_rawDesc = "" +
	"\n" +
	"\x17region_federation.proto\x12\x05proto\x1a\x0etee_mesh.proto\"\xeb\x01\n" +
	"\x16RegionDiscoveryRequest\x12#\n" +
	"\rfederation_id\x18\x01 \x01(\tR\ffederationId\x12(\n" +
	"\x10source_region_id\x18\x02 \x01(\tR\x0esourceRegionId\x12\x1f\n" +
	"\vregion_type\x18\x03 \x01(\tR\n" +
	"regionType\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12\x1f\n" +
	"\vapi_version\x18\x05 \x01(\tR\n" +
	"apiVersion\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\"\xa3\x01\n" +
	"\x17RegionDiscoveryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12+\n" +
	"\aregions\x18\x03 \x03(\v2\x11.proto.RegionInfoR\aregions\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"\xf9\x01\n" +
	"\n" +
	"RegionInfo\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\tR\bregionId\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12-\n" +
	"\x12admin_capabilities\x18\x04 \x01(\bR\x11adminCapabilities\x12*\n" +
	"\x11last_contact_time\x18\x05 \x01(\x03R\x0flastContactTime\x12\x1b\n" +
	"\ttee_count\x18\x06 \x01(\x05R\bteeCount\x12\"\n" +
	"\fcapabilities\x18\a \x03(\tR\fcapabilities\"\xb8\x02\n" +
	"\x11RegionSyncRequest\x12#\n" +
	"\rfederation_id\x18\x01 \x01(\tR\ffederationId\x12(\n" +
	"\x10source_region_id\x18\x02 \x01(\tR\x0esourceRegionId\x12\x1b\n" +
	"\tobject_id\x18\x03 \x01(\tR\bobjectId\x12#\n" +
	"\rcurrent_state\x18\x04 \x01(\fR\fcurrentState\x12#\n" +
	"\rstate_version\x18\x05 \x01(\x03R\fstateVersion\x12,\n" +
	"\tsync_mode\x18\x06 \x01(\x0e2\x0f.proto.SyncModeR\bsyncMode\x12!\n" +
	"\fdelta_update\x18\a \x01(\fR\vdeltaUpdate\x12\x1c\n" +
	"\tsignature\x18\b \x01(\fR\tsignature\"\xde\x01\n" +
	"\x12RegionSyncResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12#\n" +
	"\rupdated_state\x18\x03 \x01(\fR\fupdatedState\x12#\n" +
	"\rstate_version\x18\x04 \x01(\x03R\fstateVersion\x12!\n" +
	"\fhas_conflict\x18\x05 \x01(\bR\vhasConflict\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\"\xab\x02\n" +
	"\x13StateChangeProposal\x12#\n" +
	"\rfederation_id\x18\x01 \x01(\tR\ffederationId\x12(\n" +
	"\x10source_region_id\x18\x02 \x01(\tR\x0esourceRegionId\x12\x1b\n" +
	"\tobject_id\x18\x03 \x01(\tR\bobjectId\x12\x1b\n" +
	"\tnew_state\x18\x04 \x01(\fR\bnewState\x12#\n" +
	"\rstate_version\x18\x05 \x01(\x03R\fstateVersion\x12\x1f\n" +
	"\vproposal_id\x18\x06 \x01(\x03R\n" +
	"proposalId\x12'\n" +
	"\x0fexpiration_time\x18\a \x01(\x03R\x0eexpirationTime\x12\x1c\n" +
	"\tsignature\x18\b \x01(\fR\tsignature\"\x99\x01\n" +
	"\x13StateChangeResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12#\n" +
	"\rstate_version\x18\x03 \x01(\x03R\fstateVersion\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"\xec\x01\n" +
	"\x18FederatedSnapshotRequest\x12#\n" +
	"\rfederation_id\x18\x01 \x01(\tR\ffederationId\x12(\n" +
	"\x10source_region_id\x18\x02 \x01(\tR\x0esourceRegionId\x12%\n" +
	"\x0etarget_regions\x18\x03 \x03(\tR\rtargetRegions\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\x03R\trequestId\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\x03R\ttimeoutMs\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\"\xae\x01\n" +
	"\x19FederatedSnapshotResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x124\n" +
	"\bsnapshot\x18\x03 \x01(\v2\x18.proto.FederatedSnapshotR\bsnapshot\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"\xbd\x04\n" +
	"\x11FederatedSnapshot\x12#\n" +
	"\rfederation_id\x18\x01 \x01(\tR\ffederationId\x12\x1f\n" +
	"\vsnapshot_id\x18\x02 \x01(\fR\n" +
	"snapshotId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12^\n" +
	"\x12regional_snapshots\x18\x04 \x03(\v2/.proto.FederatedSnapshot.RegionalSnapshotsEntryR\x11regionalSnapshots\x12*\n" +
	"\x11global_state_root\x18\x05 \x01(\fR\x0fglobalStateRoot\x123\n" +
	"\x15coordinator_signature\x18\x06 \x01(\fR\x14coordinatorSignature\x12^\n" +
	"\x12consensus_metadata\x18\a \x03(\v2/.proto.FederatedSnapshot.ConsensusMetadataEntryR\x11consensusMetadata\x1a]\n" +
	"\x16RegionalSnapshotsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.proto.RegionalSnapshotR\x05value:\x028\x01\x1aD\n" +
	"\x16ConsensusMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xca\x01\n" +
	"\x10RegionalSnapshot\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\tR\bregionId\x12\x1f\n" +
	"\vsnapshot_id\x18\x02 \x01(\fR\n" +
	"snapshotId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12(\n" +
	"\x10tee_snapshot_ids\x18\x04 \x03(\fR\x0eteeSnapshotIds\x120\n" +
	"\asummary\x18\x05 \x01(\v2\x16.proto.SnapshotSummaryR\asummary\"\x97\x03\n" +
	"\x0fSnapshotSummary\x12\x1f\n" +
	"\vmerkle_root\x18\x01 \x01(\fR\n" +
	"merkleRoot\x12W\n" +
	"\x11state_root_hashes\x18\x02 \x03(\v2+.proto.SnapshotSummary.StateRootHashesEntryR\x0fstateRootHashes\x12!\n" +
	"\fobject_count\x18\x03 \x01(\x05R\vobjectCount\x12(\n" +
	"\x10total_state_size\x18\x04 \x01(\x03R\x0etotalStateSize\x12=\n" +
	"\ametrics\x18\x05 \x03(\v2#.proto.SnapshotSummary.MetricsEntryR\ametrics\x1aB\n" +
	"\x14StateRootHashesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xae\x01\n" +
	"\x1eVerifyFederatedSnapshotRequest\x12#\n" +
	"\rfederation_id\x18\x01 \x01(\tR\ffederationId\x12(\n" +
	"\x10source_region_id\x18\x02 \x01(\tR\x0esourceRegionId\x12\x1f\n" +
	"\vsnapshot_id\x18\x03 \x01(\fR\n" +
	"snapshotId\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"\xa5\x01\n" +
	"\x1fVerifyFederatedSnapshotResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12)\n" +
	"\x10regions_verified\x18\x03 \x01(\x05R\x0fregionsVerified\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"\xc1\x01\n" +
	"\x10RegionStateQuery\x12#\n" +
	"\rfederation_id\x18\x01 \x01(\tR\ffederationId\x12(\n" +
	"\x10source_region_id\x18\x02 \x01(\tR\x0esourceRegionId\x12\x1b\n" +
	"\tobject_id\x18\x03 \x01(\tR\bobjectId\x12#\n" +
	"\rinclude_state\x18\x04 \x01(\bR\fincludeState\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\"\xd9\x01\n" +
	"\x13RegionStateResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12#\n" +
	"\rstate_version\x18\x03 \x01(\x03R\fstateVersion\x12#\n" +
	"\rlast_modified\x18\x04 \x01(\x03R\flastModified\x12\x1d\n" +
	"\n" +
	"state_data\x18\x05 \x01(\fR\tstateData\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\"\xb8\x02\n" +
	"\x10ConsensusRequest\x12#\n" +
	"\rfederation_id\x18\x01 \x01(\tR\ffederationId\x12(\n" +
	"\x10source_region_id\x18\x02 \x01(\tR\x0esourceRegionId\x12\x1b\n" +
	"\tobject_id\x18\x03 \x01(\tR\bobjectId\x12%\n" +
	"\x0eproposed_value\x18\x04 \x01(\fR\rproposedValue\x12\x1f\n" +
	"\vproposal_id\x18\x05 \x01(\x03R\n" +
	"proposalId\x12'\n" +
	"\x0fexpiration_time\x18\x06 \x01(\x03R\x0eexpirationTime\x12)\n" +
	"\x10consensus_method\x18\a \x01(\tR\x0fconsensusMethod\x12\x1c\n" +
	"\tsignature\x18\b \x01(\fR\tsignature\"\xb7\x01\n" +
	"\x11ConsensusResponse\x12\x1c\n" +
	"\tagreement\x18\x01 \x01(\bR\tagreement\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12)\n" +
	"\x10counter_proposal\x18\x04 \x01(\fR\x0fcounterProposal\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\"\xa3\x01\n" +
	"\x16RegionHeartbeatRequest\x12#\n" +
	"\rfederation_id\x18\x01 \x01(\tR\ffederationId\x12(\n" +
	"\x10source_region_id\x18\x02 \x01(\tR\x0esourceRegionId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"\x8b\x01\n" +
	"\x17RegionHeartbeatResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature*1\n" +
	"\bSyncMode\x12\b\n" +
	"\x04PUSH\x10\x00\x12\b\n" +
	"\x04PULL\x10\x01\x12\x11\n" +
	"\rBIDIRECTIONAL\x10\x022\xa4\x05\n" +
	"\x10RegionFederation\x12P\n" +
	"\x0fDiscoverRegions\x12\x1d.proto.RegionDiscoveryRequest\x1a\x1e.proto.RegionDiscoveryResponse\x12G\n" +
	"\x10SynchronizeState\x12\x18.proto.RegionSyncRequest\x1a\x19.proto.RegionSyncResponse\x12L\n" +
	"\x12ProposeStateChange\x12\x1a.proto.StateChangeProposal\x1a\x1a.proto.StateChangeResponse\x12\\\n" +
	"\x17CreateFederatedSnapshot\x12\x1f.proto.FederatedSnapshotRequest\x1a .proto.FederatedSnapshotResponse\x12h\n" +
	"\x17VerifyFederatedSnapshot\x12%.proto.VerifyFederatedSnapshotRequest\x1a&.proto.VerifyFederatedSnapshotResponse\x12G\n" +
	"\x10QueryRegionState\x12\x17.proto.RegionStateQuery\x1a\x1a.proto.RegionStateResponse\x12E\n" +
	"\x10RequestConsensus\x12\x17.proto.ConsensusRequest\x1a\x18.proto.ConsensusResponse\x12O\n" +
	"\x0eHeartbeatCheck\x12\x1d.proto.RegionHeartbeatRequest\x1a\x1e.proto.RegionHeartbeatResponseB&Z$github.com/rhombus-tech/vm/tee/protob\x06proto3"

var (
	file_region_federation_proto_rawDescOnce sync.Once
	file_region_federation_proto_rawDescData []byte
)

func file_region_federation_proto_rawDescGZIP() []byte {
	file_region_federation_proto_rawDescOnce.Do(func() {
		file_region_federation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_region_federation_proto_rawDesc), len(file_region_federation_proto_rawDesc)))
	})
	return file_region_federation_proto_rawDescData
}

var file_region_federation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_region_federation_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_region_federation_proto_goTypes = []any{
	(SyncMode)(0),                           // 0: proto.SyncMode
	(*RegionDiscoveryRequest)(nil),          // 1: proto.RegionDiscoveryRequest
	(*RegionDiscoveryResponse)(nil),         // 2: proto.RegionDiscoveryResponse
	(*RegionInfo)(nil),                      // 3: proto.RegionInfo
	(*RegionSyncRequest)(nil),               // 4: proto.RegionSyncRequest
	(*RegionSyncResponse)(nil),              // 5: proto.RegionSyncResponse
	(*StateChangeProposal)(nil),             // 6: proto.StateChangeProposal
	(*StateChangeResponse)(nil),             // 7: proto.StateChangeResponse
	(*FederatedSnapshotRequest)(nil),        // 8: proto.FederatedSnapshotRequest
	(*FederatedSnapshotResponse)(nil),       // 9: proto.FederatedSnapshotResponse
	(*FederatedSnapshot)(nil),               // 10: proto.FederatedSnapshot
	(*RegionalSnapshot)(nil),                // 11: proto.RegionalSnapshot
	(*SnapshotSummary)(nil),                 // 12: proto.SnapshotSummary
	(*VerifyFederatedSnapshotRequest)(nil),  // 13: proto.VerifyFederatedSnapshotRequest
	(*VerifyFederatedSnapshotResponse)(nil), // 14: proto.VerifyFederatedSnapshotResponse
	(*RegionStateQuery)(nil),                // 15: proto.RegionStateQuery
	(*RegionStateResponse)(nil),             // 16: proto.RegionStateResponse
	(*ConsensusRequest)(nil),                // 17: proto.ConsensusRequest
	(*ConsensusResponse)(nil),               // 18: proto.ConsensusResponse
	(*RegionHeartbeatRequest)(nil),          // 19: proto.RegionHeartbeatRequest
	(*RegionHeartbeatResponse)(nil),         // 20: proto.RegionHeartbeatResponse
	nil,                                     // 21: proto.FederatedSnapshot.RegionalSnapshotsEntry
	nil,                                     // 22: proto.FederatedSnapshot.ConsensusMetadataEntry
	nil,                                     // 23: proto.SnapshotSummary.StateRootHashesEntry
	nil,                                     // 24: proto.SnapshotSummary.MetricsEntry
}
var file_region_federation_proto_depIdxs = []int32{
	3,  // 0: proto.RegionDiscoveryResponse.regions:type_name -> proto.RegionInfo
	0,  // 1: proto.RegionSyncRequest.sync_mode:type_name -> proto.SyncMode
	10, // 2: proto.FederatedSnapshotResponse.snapshot:type_name -> proto.FederatedSnapshot
	21, // 3: proto.FederatedSnapshot.regional_snapshots:type_name -> proto.FederatedSnapshot.RegionalSnapshotsEntry
	22, // 4: proto.FederatedSnapshot.consensus_metadata:type_name -> proto.FederatedSnapshot.ConsensusMetadataEntry
	12, // 5: proto.RegionalSnapshot.summary:type_name -> proto.SnapshotSummary
	23, // 6: proto.SnapshotSummary.state_root_hashes:type_name -> proto.SnapshotSummary.StateRootHashesEntry
	24, // 7: proto.SnapshotSummary.metrics:type_name -> proto.SnapshotSummary.MetricsEntry
	11, // 8: proto.FederatedSnapshot.RegionalSnapshotsEntry.value:type_name -> proto.RegionalSnapshot
	1,  // 9: proto.RegionFederation.DiscoverRegions:input_type -> proto.RegionDiscoveryRequest
	4,  // 10: proto.RegionFederation.SynchronizeState:input_type -> proto.RegionSyncRequest
	6,  // 11: proto.RegionFederation.ProposeStateChange:input_type -> proto.StateChangeProposal
	8,  // 12: proto.RegionFederation.CreateFederatedSnapshot:input_type -> proto.FederatedSnapshotRequest
	13, // 13: proto.RegionFederation.VerifyFederatedSnapshot:input_type -> proto.VerifyFederatedSnapshotRequest
	15, // 14: proto.RegionFederation.QueryRegionState:input_type -> proto.RegionStateQuery
	17, // 15: proto.RegionFederation.RequestConsensus:input_type -> proto.ConsensusRequest
	19, // 16: proto.RegionFederation.HeartbeatCheck:input_type -> proto.RegionHeartbeatRequest
	2,  // 17: proto.RegionFederation.DiscoverRegions:output_type -> proto.RegionDiscoveryResponse
	5,  // 18: proto.RegionFederation.SynchronizeState:output_type -> proto.RegionSyncResponse
	7,  // 19: proto.RegionFederation.ProposeStateChange:output_type -> proto.StateChangeResponse
	9,  // 20: proto.RegionFederation.CreateFederatedSnapshot:output_type -> proto.FederatedSnapshotResponse
	14, // 21: proto.RegionFederation.VerifyFederatedSnapshot:output_type -> proto.VerifyFederatedSnapshotResponse
	16, // 22: proto.RegionFederation.QueryRegionState:output_type -> proto.RegionStateResponse
	18, // 23: proto.RegionFederation.RequestConsensus:output_type -> proto.ConsensusResponse
	20, // 24: proto.RegionFederation.HeartbeatCheck:output_type -> proto.RegionHeartbeatResponse
	17, // [17:25] is the sub-list for method output_type
	9,  // [9:17] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_region_federation_proto_init() }
func file_region_federation_proto_init() {
	if File_region_federation_proto != nil {
		return
	}
	// Skip tee_mesh initialization since it's causing problems
	// file_tee_mesh_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_region_federation_proto_rawDesc), len(file_region_federation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_region_federation_proto_goTypes,
		DependencyIndexes: file_region_federation_proto_depIdxs,
		EnumInfos:         file_region_federation_proto_enumTypes,
		MessageInfos:      file_region_federation_proto_msgTypes,
	}.Build()
	File_region_federation_proto = out.File
	file_region_federation_proto_goTypes = nil
	file_region_federation_proto_depIdxs = nil
}
