// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.2
// source: merkle_sync.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TeeMesh_SyncOptimized_FullMethodName = "/proto.TeeMesh/SyncOptimized"
	TeeMesh_GossipSync_FullMethodName    = "/proto.TeeMesh/GossipSync"
)

// TeeMeshClient is the client API for TeeMesh service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Extend the TeeMesh service with optimized sync capabilities
type TeeMeshClient interface {
	// SyncOptimized provides an optimized state synchronization
	SyncOptimized(ctx context.Context, in *SyncOptimizedRequest, opts ...grpc.CallOption) (*SyncOptimizedResponse, error)
	// GossipSync propagates updates between peers
	GossipSync(ctx context.Context, in *GossipSyncMessage, opts ...grpc.CallOption) (*SyncOptimizedResponse, error)
}

type teeMeshClient struct {
	cc grpc.ClientConnInterface
}

func NewTeeMeshClient(cc grpc.ClientConnInterface) TeeMeshClient {
	return &teeMeshClient{cc}
}

func (c *teeMeshClient) SyncOptimized(ctx context.Context, in *SyncOptimizedRequest, opts ...grpc.CallOption) (*SyncOptimizedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncOptimizedResponse)
	err := c.cc.Invoke(ctx, TeeMesh_SyncOptimized_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teeMeshClient) GossipSync(ctx context.Context, in *GossipSyncMessage, opts ...grpc.CallOption) (*SyncOptimizedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncOptimizedResponse)
	err := c.cc.Invoke(ctx, TeeMesh_GossipSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TeeMeshServer is the server API for TeeMesh service.
// All implementations must embed UnimplementedTeeMeshServer
// for forward compatibility.
//
// Extend the TeeMesh service with optimized sync capabilities
type TeeMeshServer interface {
	// SyncOptimized provides an optimized state synchronization
	SyncOptimized(context.Context, *SyncOptimizedRequest) (*SyncOptimizedResponse, error)
	// GossipSync propagates updates between peers
	GossipSync(context.Context, *GossipSyncMessage) (*SyncOptimizedResponse, error)
	mustEmbedUnimplementedTeeMeshServer()
}

// UnimplementedTeeMeshServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTeeMeshServer struct{}

func (UnimplementedTeeMeshServer) SyncOptimized(context.Context, *SyncOptimizedRequest) (*SyncOptimizedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncOptimized not implemented")
}
func (UnimplementedTeeMeshServer) GossipSync(context.Context, *GossipSyncMessage) (*SyncOptimizedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GossipSync not implemented")
}
func (UnimplementedTeeMeshServer) mustEmbedUnimplementedTeeMeshServer() {}
func (UnimplementedTeeMeshServer) testEmbeddedByValue()                 {}

// UnsafeTeeMeshServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TeeMeshServer will
// result in compilation errors.
type UnsafeTeeMeshServer interface {
	mustEmbedUnimplementedTeeMeshServer()
}

func RegisterTeeMeshServer(s grpc.ServiceRegistrar, srv TeeMeshServer) {
	// If the following call pancis, it indicates UnimplementedTeeMeshServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TeeMesh_ServiceDesc, srv)
}

func _TeeMesh_SyncOptimized_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncOptimizedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeeMeshServer).SyncOptimized(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeeMesh_SyncOptimized_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeeMeshServer).SyncOptimized(ctx, req.(*SyncOptimizedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeeMesh_GossipSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GossipSyncMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeeMeshServer).GossipSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeeMesh_GossipSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeeMeshServer).GossipSync(ctx, req.(*GossipSyncMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// TeeMesh_ServiceDesc is the grpc.ServiceDesc for TeeMesh service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TeeMesh_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TeeMesh",
	HandlerType: (*TeeMeshServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncOptimized",
			Handler:    _TeeMesh_SyncOptimized_Handler,
		},
		{
			MethodName: "GossipSync",
			Handler:    _TeeMesh_GossipSync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "merkle_sync.proto",
}
