// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.2
// source: merkle_sync.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DiffOperation represents the type of operation in a differential update
type DiffOperation int32

const (
	DiffOperation_DIFF_OP_ADD       DiffOperation = 0
	DiffOperation_DIFF_OP_REMOVE    DiffOperation = 1
	DiffOperation_DIFF_OP_MODIFY    DiffOperation = 2
	DiffOperation_DIFF_OP_UNCHANGED DiffOperation = 3
)

// Enum value maps for DiffOperation.
var (
	DiffOperation_name = map[int32]string{
		0: "DIFF_OP_ADD",
		1: "DIFF_OP_REMOVE",
		2: "DIFF_OP_MODIFY",
		3: "DIFF_OP_UNCHANGED",
	}
	DiffOperation_value = map[string]int32{
		"DIFF_OP_ADD":       0,
		"DIFF_OP_REMOVE":    1,
		"DIFF_OP_MODIFY":    2,
		"DIFF_OP_UNCHANGED": 3,
	}
)

func (x DiffOperation) Enum() *DiffOperation {
	p := new(DiffOperation)
	*p = x
	return p
}

func (x DiffOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiffOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_merkle_sync_proto_enumTypes[0].Descriptor()
}

func (DiffOperation) Type() protoreflect.EnumType {
	return &file_merkle_sync_proto_enumTypes[0]
}

func (x DiffOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiffOperation.Descriptor instead.
func (DiffOperation) EnumDescriptor() ([]byte, []int) {
	return file_merkle_sync_proto_rawDescGZIP(), []int{0}
}

// MerkleProofMessage contains proof data for an object in the Merkle tree
type MerkleProofMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	ProofPath     [][]byte               `protobuf:"bytes,2,rep,name=proof_path,json=proofPath,proto3" json:"proof_path,omitempty"`
	RootHash      []byte                 `protobuf:"bytes,3,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	ObjectHash    []byte                 `protobuf:"bytes,4,opt,name=object_hash,json=objectHash,proto3" json:"object_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleProofMessage) Reset() {
	*x = MerkleProofMessage{}
	mi := &file_merkle_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleProofMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleProofMessage) ProtoMessage() {}

func (x *MerkleProofMessage) ProtoReflect() protoreflect.Message {
	mi := &file_merkle_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleProofMessage.ProtoReflect.Descriptor instead.
func (*MerkleProofMessage) Descriptor() ([]byte, []int) {
	return file_merkle_sync_proto_rawDescGZIP(), []int{0}
}

func (x *MerkleProofMessage) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *MerkleProofMessage) GetProofPath() [][]byte {
	if x != nil {
		return x.ProofPath
	}
	return nil
}

func (x *MerkleProofMessage) GetRootHash() []byte {
	if x != nil {
		return x.RootHash
	}
	return nil
}

func (x *MerkleProofMessage) GetObjectHash() []byte {
	if x != nil {
		return x.ObjectHash
	}
	return nil
}

// DomainProofMessage contains proof data for a domain
type DomainProofMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DomainId      string                 `protobuf:"bytes,1,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	Proof         *MerkleProofMessage    `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainProofMessage) Reset() {
	*x = DomainProofMessage{}
	mi := &file_merkle_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainProofMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainProofMessage) ProtoMessage() {}

func (x *DomainProofMessage) ProtoReflect() protoreflect.Message {
	mi := &file_merkle_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainProofMessage.ProtoReflect.Descriptor instead.
func (*DomainProofMessage) Descriptor() ([]byte, []int) {
	return file_merkle_sync_proto_rawDescGZIP(), []int{1}
}

func (x *DomainProofMessage) GetDomainId() string {
	if x != nil {
		return x.DomainId
	}
	return ""
}

func (x *DomainProofMessage) GetProof() *MerkleProofMessage {
	if x != nil {
		return x.Proof
	}
	return nil
}

// EnhancedDifferentialUpdate represents an optimized state update with Merkle proofs
type EnhancedDifferentialUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Base differential update
	BaseSnapshotId   []byte                 `protobuf:"bytes,1,opt,name=base_snapshot_id,json=baseSnapshotId,proto3" json:"base_snapshot_id,omitempty"`
	TargetSnapshotId []byte                 `protobuf:"bytes,2,opt,name=target_snapshot_id,json=targetSnapshotId,proto3" json:"target_snapshot_id,omitempty"`
	Timestamp        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Object changes
	ObjectChanges     map[string]*ObjectDiffMessage `protobuf:"bytes,4,rep,name=object_changes,json=objectChanges,proto3" json:"object_changes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StateReferences   map[string][]byte             `protobuf:"bytes,5,rep,name=state_references,json=stateReferences,proto3" json:"state_references,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ChangedObjectsRaw map[string][]byte             `protobuf:"bytes,6,rep,name=changed_objects_raw,json=changedObjectsRaw,proto3" json:"changed_objects_raw,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Merkle verification data
	MerkleRoot   []byte                `protobuf:"bytes,7,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	DomainProofs []*DomainProofMessage `protobuf:"bytes,8,rep,name=domain_proofs,json=domainProofs,proto3" json:"domain_proofs,omitempty"`
	// Metadata
	Metadata      map[string]string `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Size          int64             `protobuf:"varint,10,opt,name=size,proto3" json:"size,omitempty"`
	Checksum      []byte            `protobuf:"bytes,11,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnhancedDifferentialUpdate) Reset() {
	*x = EnhancedDifferentialUpdate{}
	mi := &file_merkle_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnhancedDifferentialUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnhancedDifferentialUpdate) ProtoMessage() {}

func (x *EnhancedDifferentialUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_merkle_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnhancedDifferentialUpdate.ProtoReflect.Descriptor instead.
func (*EnhancedDifferentialUpdate) Descriptor() ([]byte, []int) {
	return file_merkle_sync_proto_rawDescGZIP(), []int{2}
}

func (x *EnhancedDifferentialUpdate) GetBaseSnapshotId() []byte {
	if x != nil {
		return x.BaseSnapshotId
	}
	return nil
}

func (x *EnhancedDifferentialUpdate) GetTargetSnapshotId() []byte {
	if x != nil {
		return x.TargetSnapshotId
	}
	return nil
}

func (x *EnhancedDifferentialUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *EnhancedDifferentialUpdate) GetObjectChanges() map[string]*ObjectDiffMessage {
	if x != nil {
		return x.ObjectChanges
	}
	return nil
}

func (x *EnhancedDifferentialUpdate) GetStateReferences() map[string][]byte {
	if x != nil {
		return x.StateReferences
	}
	return nil
}

func (x *EnhancedDifferentialUpdate) GetChangedObjectsRaw() map[string][]byte {
	if x != nil {
		return x.ChangedObjectsRaw
	}
	return nil
}

func (x *EnhancedDifferentialUpdate) GetMerkleRoot() []byte {
	if x != nil {
		return x.MerkleRoot
	}
	return nil
}

func (x *EnhancedDifferentialUpdate) GetDomainProofs() []*DomainProofMessage {
	if x != nil {
		return x.DomainProofs
	}
	return nil
}

func (x *EnhancedDifferentialUpdate) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *EnhancedDifferentialUpdate) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *EnhancedDifferentialUpdate) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

// ObjectDiffMessage represents changes to a single object
type ObjectDiffMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Operation     DiffOperation          `protobuf:"varint,2,opt,name=operation,proto3,enum=proto.DiffOperation" json:"operation,omitempty"`
	PreviousHash  []byte                 `protobuf:"bytes,3,opt,name=previous_hash,json=previousHash,proto3" json:"previous_hash,omitempty"`
	CurrentHash   []byte                 `protobuf:"bytes,4,opt,name=current_hash,json=currentHash,proto3" json:"current_hash,omitempty"`
	SizeDelta     int64                  `protobuf:"varint,5,opt,name=size_delta,json=sizeDelta,proto3" json:"size_delta,omitempty"`
	IsBinary      bool                   `protobuf:"varint,6,opt,name=is_binary,json=isBinary,proto3" json:"is_binary,omitempty"`
	FieldChanges  []*FieldChangeMessage  `protobuf:"bytes,7,rep,name=field_changes,json=fieldChanges,proto3" json:"field_changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectDiffMessage) Reset() {
	*x = ObjectDiffMessage{}
	mi := &file_merkle_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectDiffMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectDiffMessage) ProtoMessage() {}

func (x *ObjectDiffMessage) ProtoReflect() protoreflect.Message {
	mi := &file_merkle_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectDiffMessage.ProtoReflect.Descriptor instead.
func (*ObjectDiffMessage) Descriptor() ([]byte, []int) {
	return file_merkle_sync_proto_rawDescGZIP(), []int{3}
}

func (x *ObjectDiffMessage) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *ObjectDiffMessage) GetOperation() DiffOperation {
	if x != nil {
		return x.Operation
	}
	return DiffOperation_DIFF_OP_ADD
}

func (x *ObjectDiffMessage) GetPreviousHash() []byte {
	if x != nil {
		return x.PreviousHash
	}
	return nil
}

func (x *ObjectDiffMessage) GetCurrentHash() []byte {
	if x != nil {
		return x.CurrentHash
	}
	return nil
}

func (x *ObjectDiffMessage) GetSizeDelta() int64 {
	if x != nil {
		return x.SizeDelta
	}
	return 0
}

func (x *ObjectDiffMessage) GetIsBinary() bool {
	if x != nil {
		return x.IsBinary
	}
	return false
}

func (x *ObjectDiffMessage) GetFieldChanges() []*FieldChangeMessage {
	if x != nil {
		return x.FieldChanges
	}
	return nil
}

// FieldChangeMessage represents a change to a field in a structured object
type FieldChangeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldPath     string                 `protobuf:"bytes,1,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	Operation     DiffOperation          `protobuf:"varint,2,opt,name=operation,proto3,enum=proto.DiffOperation" json:"operation,omitempty"`
	PreviousValue []byte                 `protobuf:"bytes,3,opt,name=previous_value,json=previousValue,proto3" json:"previous_value,omitempty"`
	CurrentValue  []byte                 `protobuf:"bytes,4,opt,name=current_value,json=currentValue,proto3" json:"current_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldChangeMessage) Reset() {
	*x = FieldChangeMessage{}
	mi := &file_merkle_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldChangeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldChangeMessage) ProtoMessage() {}

func (x *FieldChangeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_merkle_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldChangeMessage.ProtoReflect.Descriptor instead.
func (*FieldChangeMessage) Descriptor() ([]byte, []int) {
	return file_merkle_sync_proto_rawDescGZIP(), []int{4}
}

func (x *FieldChangeMessage) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

func (x *FieldChangeMessage) GetOperation() DiffOperation {
	if x != nil {
		return x.Operation
	}
	return DiffOperation_DIFF_OP_ADD
}

func (x *FieldChangeMessage) GetPreviousValue() []byte {
	if x != nil {
		return x.PreviousValue
	}
	return nil
}

func (x *FieldChangeMessage) GetCurrentValue() []byte {
	if x != nil {
		return x.CurrentValue
	}
	return nil
}

// SyncOptimizedRequest optimizes state sync with domain-based partitioning and gossip
type SyncOptimizedRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceTeeId    string                 `protobuf:"bytes,1,opt,name=source_tee_id,json=sourceTeeId,proto3" json:"source_tee_id,omitempty"`
	BaseSnapshotId []byte                 `protobuf:"bytes,2,opt,name=base_snapshot_id,json=baseSnapshotId,proto3" json:"base_snapshot_id,omitempty"`
	Domains        []string               `protobuf:"bytes,3,rep,name=domains,proto3" json:"domains,omitempty"`                                     // Only sync specific domains if provided
	ForceFullSync  bool                   `protobuf:"varint,4,opt,name=force_full_sync,json=forceFullSync,proto3" json:"force_full_sync,omitempty"` // Force full sync even if partial sync is possible
	MaxDiffSize    int32                  `protobuf:"varint,5,opt,name=max_diff_size,json=maxDiffSize,proto3" json:"max_diff_size,omitempty"`       // Maximum diff size in bytes (0 = no limit)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncOptimizedRequest) Reset() {
	*x = SyncOptimizedRequest{}
	mi := &file_merkle_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncOptimizedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOptimizedRequest) ProtoMessage() {}

func (x *SyncOptimizedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merkle_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOptimizedRequest.ProtoReflect.Descriptor instead.
func (*SyncOptimizedRequest) Descriptor() ([]byte, []int) {
	return file_merkle_sync_proto_rawDescGZIP(), []int{5}
}

func (x *SyncOptimizedRequest) GetSourceTeeId() string {
	if x != nil {
		return x.SourceTeeId
	}
	return ""
}

func (x *SyncOptimizedRequest) GetBaseSnapshotId() []byte {
	if x != nil {
		return x.BaseSnapshotId
	}
	return nil
}

func (x *SyncOptimizedRequest) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *SyncOptimizedRequest) GetForceFullSync() bool {
	if x != nil {
		return x.ForceFullSync
	}
	return false
}

func (x *SyncOptimizedRequest) GetMaxDiffSize() int32 {
	if x != nil {
		return x.MaxDiffSize
	}
	return 0
}

// SyncOptimizedResponse contains optimized differential updates
type SyncOptimizedResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	SourceTeeId   string                      `protobuf:"bytes,1,opt,name=source_tee_id,json=sourceTeeId,proto3" json:"source_tee_id,omitempty"`
	Success       bool                        `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                      `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	DiffUpdate    *EnhancedDifferentialUpdate `protobuf:"bytes,4,opt,name=diff_update,json=diffUpdate,proto3" json:"diff_update,omitempty"`
	IsPartial     bool                        `protobuf:"varint,5,opt,name=is_partial,json=isPartial,proto3" json:"is_partial,omitempty"`            // Whether this is a partial update
	SyncedDomains []string                    `protobuf:"bytes,6,rep,name=synced_domains,json=syncedDomains,proto3" json:"synced_domains,omitempty"` // Domains included in this update
	SyncTime      *timestamppb.Timestamp      `protobuf:"bytes,7,opt,name=sync_time,json=syncTime,proto3" json:"sync_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncOptimizedResponse) Reset() {
	*x = SyncOptimizedResponse{}
	mi := &file_merkle_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncOptimizedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOptimizedResponse) ProtoMessage() {}

func (x *SyncOptimizedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merkle_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOptimizedResponse.ProtoReflect.Descriptor instead.
func (*SyncOptimizedResponse) Descriptor() ([]byte, []int) {
	return file_merkle_sync_proto_rawDescGZIP(), []int{6}
}

func (x *SyncOptimizedResponse) GetSourceTeeId() string {
	if x != nil {
		return x.SourceTeeId
	}
	return ""
}

func (x *SyncOptimizedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncOptimizedResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SyncOptimizedResponse) GetDiffUpdate() *EnhancedDifferentialUpdate {
	if x != nil {
		return x.DiffUpdate
	}
	return nil
}

func (x *SyncOptimizedResponse) GetIsPartial() bool {
	if x != nil {
		return x.IsPartial
	}
	return false
}

func (x *SyncOptimizedResponse) GetSyncedDomains() []string {
	if x != nil {
		return x.SyncedDomains
	}
	return nil
}

func (x *SyncOptimizedResponse) GetSyncTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SyncTime
	}
	return nil
}

// GossipSyncMessage enables efficient propagation of updates between peers
type GossipSyncMessage struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	OriginatorId  string                      `protobuf:"bytes,1,opt,name=originator_id,json=originatorId,proto3" json:"originator_id,omitempty"` // Original source TEE ID
	TargetIds     []string                    `protobuf:"bytes,2,rep,name=target_ids,json=targetIds,proto3" json:"target_ids,omitempty"`          // Intended recipients (empty = broadcast)
	DiffUpdate    *EnhancedDifferentialUpdate `protobuf:"bytes,3,opt,name=diff_update,json=diffUpdate,proto3" json:"diff_update,omitempty"`
	HopCount      int32                       `protobuf:"varint,4,opt,name=hop_count,json=hopCount,proto3" json:"hop_count,omitempty"` // Number of hops this update has taken
	MaxHops       int32                       `protobuf:"varint,5,opt,name=max_hops,json=maxHops,proto3" json:"max_hops,omitempty"`    // Maximum number of hops (TTL)
	Timestamp     *timestamppb.Timestamp      `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipSyncMessage) Reset() {
	*x = GossipSyncMessage{}
	mi := &file_merkle_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipSyncMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipSyncMessage) ProtoMessage() {}

func (x *GossipSyncMessage) ProtoReflect() protoreflect.Message {
	mi := &file_merkle_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipSyncMessage.ProtoReflect.Descriptor instead.
func (*GossipSyncMessage) Descriptor() ([]byte, []int) {
	return file_merkle_sync_proto_rawDescGZIP(), []int{7}
}

func (x *GossipSyncMessage) GetOriginatorId() string {
	if x != nil {
		return x.OriginatorId
	}
	return ""
}

func (x *GossipSyncMessage) GetTargetIds() []string {
	if x != nil {
		return x.TargetIds
	}
	return nil
}

func (x *GossipSyncMessage) GetDiffUpdate() *EnhancedDifferentialUpdate {
	if x != nil {
		return x.DiffUpdate
	}
	return nil
}

func (x *GossipSyncMessage) GetHopCount() int32 {
	if x != nil {
		return x.HopCount
	}
	return 0
}

func (x *GossipSyncMessage) GetMaxHops() int32 {
	if x != nil {
		return x.MaxHops
	}
	return 0
}

func (x *GossipSyncMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_merkle_sync_proto protoreflect.FileDescriptor

const file_merkle_sync_proto_rawDesc = "" +
	"\n" +
	"\x11merkle_sync.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8e\x01\n" +
	"\x12MerkleProofMessage\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\x12\x1d\n" +
	"\n" +
	"proof_path\x18\x02 \x03(\fR\tproofPath\x12\x1b\n" +
	"\troot_hash\x18\x03 \x01(\fR\brootHash\x12\x1f\n" +
	"\vobject_hash\x18\x04 \x01(\fR\n" +
	"objectHash\"b\n" +
	"\x12DomainProofMessage\x12\x1b\n" +
	"\tdomain_id\x18\x01 \x01(\tR\bdomainId\x12/\n" +
	"\x05proof\x18\x02 \x01(\v2\x19.proto.MerkleProofMessageR\x05proof\"\xd9\a\n" +
	"\x1aEnhancedDifferentialUpdate\x12(\n" +
	"\x10base_snapshot_id\x18\x01 \x01(\fR\x0ebaseSnapshotId\x12,\n" +
	"\x12target_snapshot_id\x18\x02 \x01(\fR\x10targetSnapshotId\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12[\n" +
	"\x0eobject_changes\x18\x04 \x03(\v24.proto.EnhancedDifferentialUpdate.ObjectChangesEntryR\robjectChanges\x12a\n" +
	"\x10state_references\x18\x05 \x03(\v26.proto.EnhancedDifferentialUpdate.StateReferencesEntryR\x0fstateReferences\x12h\n" +
	"\x13changed_objects_raw\x18\x06 \x03(\v28.proto.EnhancedDifferentialUpdate.ChangedObjectsRawEntryR\x11changedObjectsRaw\x12\x1f\n" +
	"\vmerkle_root\x18\a \x01(\fR\n" +
	"merkleRoot\x12>\n" +
	"\rdomain_proofs\x18\b \x03(\v2\x19.proto.DomainProofMessageR\fdomainProofs\x12K\n" +
	"\bmetadata\x18\t \x03(\v2/.proto.EnhancedDifferentialUpdate.MetadataEntryR\bmetadata\x12\x12\n" +
	"\x04size\x18\n" +
	" \x01(\x03R\x04size\x12\x1a\n" +
	"\bchecksum\x18\v \x01(\fR\bchecksum\x1aZ\n" +
	"\x12ObjectChangesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.proto.ObjectDiffMessageR\x05value:\x028\x01\x1aB\n" +
	"\x14StateReferencesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1aD\n" +
	"\x16ChangedObjectsRawEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa8\x02\n" +
	"\x11ObjectDiffMessage\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\x122\n" +
	"\toperation\x18\x02 \x01(\x0e2\x14.proto.DiffOperationR\toperation\x12#\n" +
	"\rprevious_hash\x18\x03 \x01(\fR\fpreviousHash\x12!\n" +
	"\fcurrent_hash\x18\x04 \x01(\fR\vcurrentHash\x12\x1d\n" +
	"\n" +
	"size_delta\x18\x05 \x01(\x03R\tsizeDelta\x12\x1b\n" +
	"\tis_binary\x18\x06 \x01(\bR\bisBinary\x12>\n" +
	"\rfield_changes\x18\a \x03(\v2\x19.proto.FieldChangeMessageR\ffieldChanges\"\xb3\x01\n" +
	"\x12FieldChangeMessage\x12\x1d\n" +
	"\n" +
	"field_path\x18\x01 \x01(\tR\tfieldPath\x122\n" +
	"\toperation\x18\x02 \x01(\x0e2\x14.proto.DiffOperationR\toperation\x12%\n" +
	"\x0eprevious_value\x18\x03 \x01(\fR\rpreviousValue\x12#\n" +
	"\rcurrent_value\x18\x04 \x01(\fR\fcurrentValue\"\xca\x01\n" +
	"\x14SyncOptimizedRequest\x12\"\n" +
	"\rsource_tee_id\x18\x01 \x01(\tR\vsourceTeeId\x12(\n" +
	"\x10base_snapshot_id\x18\x02 \x01(\fR\x0ebaseSnapshotId\x12\x18\n" +
	"\adomains\x18\x03 \x03(\tR\adomains\x12&\n" +
	"\x0fforce_full_sync\x18\x04 \x01(\bR\rforceFullSync\x12\"\n" +
	"\rmax_diff_size\x18\x05 \x01(\x05R\vmaxDiffSize\"\xbd\x02\n" +
	"\x15SyncOptimizedResponse\x12\"\n" +
	"\rsource_tee_id\x18\x01 \x01(\tR\vsourceTeeId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12B\n" +
	"\vdiff_update\x18\x04 \x01(\v2!.proto.EnhancedDifferentialUpdateR\n" +
	"diffUpdate\x12\x1d\n" +
	"\n" +
	"is_partial\x18\x05 \x01(\bR\tisPartial\x12%\n" +
	"\x0esynced_domains\x18\x06 \x03(\tR\rsyncedDomains\x127\n" +
	"\tsync_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bsyncTime\"\x8d\x02\n" +
	"\x11GossipSyncMessage\x12#\n" +
	"\roriginator_id\x18\x01 \x01(\tR\foriginatorId\x12\x1d\n" +
	"\n" +
	"target_ids\x18\x02 \x03(\tR\ttargetIds\x12B\n" +
	"\vdiff_update\x18\x03 \x01(\v2!.proto.EnhancedDifferentialUpdateR\n" +
	"diffUpdate\x12\x1b\n" +
	"\thop_count\x18\x04 \x01(\x05R\bhopCount\x12\x19\n" +
	"\bmax_hops\x18\x05 \x01(\x05R\amaxHops\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp*_\n" +
	"\rDiffOperation\x12\x0f\n" +
	"\vDIFF_OP_ADD\x10\x00\x12\x12\n" +
	"\x0eDIFF_OP_REMOVE\x10\x01\x12\x12\n" +
	"\x0eDIFF_OP_MODIFY\x10\x02\x12\x15\n" +
	"\x11DIFF_OP_UNCHANGED\x10\x032\x9f\x01\n" +
	"\aTeeMesh\x12L\n" +
	"\rSyncOptimized\x12\x1b.proto.SyncOptimizedRequest\x1a\x1c.proto.SyncOptimizedResponse\"\x00\x12F\n" +
	"\n" +
	"GossipSync\x12\x18.proto.GossipSyncMessage\x1a\x1c.proto.SyncOptimizedResponse\"\x00B&Z$github.com/rhombus-tech/vm/tee/protob\x06proto3"

var (
	file_merkle_sync_proto_rawDescOnce sync.Once
	file_merkle_sync_proto_rawDescData []byte
)

func file_merkle_sync_proto_rawDescGZIP() []byte {
	file_merkle_sync_proto_rawDescOnce.Do(func() {
		file_merkle_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_merkle_sync_proto_rawDesc), len(file_merkle_sync_proto_rawDesc)))
	})
	return file_merkle_sync_proto_rawDescData
}

var file_merkle_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_merkle_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_merkle_sync_proto_goTypes = []any{
	(DiffOperation)(0),                 // 0: proto.DiffOperation
	(*MerkleProofMessage)(nil),         // 1: proto.MerkleProofMessage
	(*DomainProofMessage)(nil),         // 2: proto.DomainProofMessage
	(*EnhancedDifferentialUpdate)(nil), // 3: proto.EnhancedDifferentialUpdate
	(*ObjectDiffMessage)(nil),          // 4: proto.ObjectDiffMessage
	(*FieldChangeMessage)(nil),         // 5: proto.FieldChangeMessage
	(*SyncOptimizedRequest)(nil),       // 6: proto.SyncOptimizedRequest
	(*SyncOptimizedResponse)(nil),      // 7: proto.SyncOptimizedResponse
	(*GossipSyncMessage)(nil),          // 8: proto.GossipSyncMessage
	nil,                                // 9: proto.EnhancedDifferentialUpdate.ObjectChangesEntry
	nil,                                // 10: proto.EnhancedDifferentialUpdate.StateReferencesEntry
	nil,                                // 11: proto.EnhancedDifferentialUpdate.ChangedObjectsRawEntry
	nil,                                // 12: proto.EnhancedDifferentialUpdate.MetadataEntry
	(*timestamppb.Timestamp)(nil),      // 13: google.protobuf.Timestamp
}
var file_merkle_sync_proto_depIdxs = []int32{
	1,  // 0: proto.DomainProofMessage.proof:type_name -> proto.MerkleProofMessage
	13, // 1: proto.EnhancedDifferentialUpdate.timestamp:type_name -> google.protobuf.Timestamp
	9,  // 2: proto.EnhancedDifferentialUpdate.object_changes:type_name -> proto.EnhancedDifferentialUpdate.ObjectChangesEntry
	10, // 3: proto.EnhancedDifferentialUpdate.state_references:type_name -> proto.EnhancedDifferentialUpdate.StateReferencesEntry
	11, // 4: proto.EnhancedDifferentialUpdate.changed_objects_raw:type_name -> proto.EnhancedDifferentialUpdate.ChangedObjectsRawEntry
	2,  // 5: proto.EnhancedDifferentialUpdate.domain_proofs:type_name -> proto.DomainProofMessage
	12, // 6: proto.EnhancedDifferentialUpdate.metadata:type_name -> proto.EnhancedDifferentialUpdate.MetadataEntry
	0,  // 7: proto.ObjectDiffMessage.operation:type_name -> proto.DiffOperation
	5,  // 8: proto.ObjectDiffMessage.field_changes:type_name -> proto.FieldChangeMessage
	0,  // 9: proto.FieldChangeMessage.operation:type_name -> proto.DiffOperation
	3,  // 10: proto.SyncOptimizedResponse.diff_update:type_name -> proto.EnhancedDifferentialUpdate
	13, // 11: proto.SyncOptimizedResponse.sync_time:type_name -> google.protobuf.Timestamp
	3,  // 12: proto.GossipSyncMessage.diff_update:type_name -> proto.EnhancedDifferentialUpdate
	13, // 13: proto.GossipSyncMessage.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 14: proto.EnhancedDifferentialUpdate.ObjectChangesEntry.value:type_name -> proto.ObjectDiffMessage
	6,  // 15: proto.TeeMesh.SyncOptimized:input_type -> proto.SyncOptimizedRequest
	8,  // 16: proto.TeeMesh.GossipSync:input_type -> proto.GossipSyncMessage
	7,  // 17: proto.TeeMesh.SyncOptimized:output_type -> proto.SyncOptimizedResponse
	7,  // 18: proto.TeeMesh.GossipSync:output_type -> proto.SyncOptimizedResponse
	17, // [17:19] is the sub-list for method output_type
	15, // [15:17] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_merkle_sync_proto_init() }
func file_merkle_sync_proto_init() {
	if File_merkle_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merkle_sync_proto_rawDesc), len(file_merkle_sync_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_merkle_sync_proto_goTypes,
		DependencyIndexes: file_merkle_sync_proto_depIdxs,
		EnumInfos:         file_merkle_sync_proto_enumTypes,
		MessageInfos:      file_merkle_sync_proto_msgTypes,
	}.Build()
	File_merkle_sync_proto = out.File
	file_merkle_sync_proto_goTypes = nil
	file_merkle_sync_proto_depIdxs = nil
}
