// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.2
// source: tee_mesh.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TeeMesh_Discover_FullMethodName      = "/proto.TeeMesh/Discover"
	TeeMesh_DirectExecute_FullMethodName = "/proto.TeeMesh/DirectExecute"
	TeeMesh_Ping_FullMethodName          = "/proto.TeeMesh/Ping"
	TeeMesh_Sync_FullMethodName          = "/proto.TeeMesh/Sync"
	TeeMesh_Heartbeat_FullMethodName     = "/proto.TeeMesh/Heartbeat"
	TeeMesh_GetPeers_FullMethodName      = "/proto.TeeMesh/GetPeers"
)

// TeeMeshClient is the client API for TeeMesh service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TeeMesh service manages direct communication between TEEs
type TeeMeshClient interface {
	// Discover allows TEEs to find each other within the same region
	Discover(ctx context.Context, in *DiscoveryRequest, opts ...grpc.CallOption) (*DiscoveryResponse, error)
	// DirectExecute allows one TEE to directly execute operations on another
	DirectExecute(ctx context.Context, in *DirectExecutionRequest, opts ...grpc.CallOption) (*DirectExecutionResponse, error)
	// Ping is a simple health check
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// Sync syncs state between TEEs
	Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	// Heartbeat sends and receives TEE attestation and status updates
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// GetPeers retrieves a list of attested peers in the region
	GetPeers(ctx context.Context, in *GetPeersRequest, opts ...grpc.CallOption) (*GetPeersResponse, error)
}

type teeMeshClient struct {
	cc grpc.ClientConnInterface
}

func NewTeeMeshClient(cc grpc.ClientConnInterface) TeeMeshClient {
	return &teeMeshClient{cc}
}

func (c *teeMeshClient) Discover(ctx context.Context, in *DiscoveryRequest, opts ...grpc.CallOption) (*DiscoveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscoveryResponse)
	err := c.cc.Invoke(ctx, TeeMesh_Discover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teeMeshClient) DirectExecute(ctx context.Context, in *DirectExecutionRequest, opts ...grpc.CallOption) (*DirectExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DirectExecutionResponse)
	err := c.cc.Invoke(ctx, TeeMesh_DirectExecute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teeMeshClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, TeeMesh_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teeMeshClient) Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, TeeMesh_Sync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teeMeshClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, TeeMesh_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teeMeshClient) GetPeers(ctx context.Context, in *GetPeersRequest, opts ...grpc.CallOption) (*GetPeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPeersResponse)
	err := c.cc.Invoke(ctx, TeeMesh_GetPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TeeMeshServer is the server API for TeeMesh service.
// All implementations must embed UnimplementedTeeMeshServer
// for forward compatibility.
//
// TeeMesh service manages direct communication between TEEs
type TeeMeshServer interface {
	// Discover allows TEEs to find each other within the same region
	Discover(context.Context, *DiscoveryRequest) (*DiscoveryResponse, error)
	// DirectExecute allows one TEE to directly execute operations on another
	DirectExecute(context.Context, *DirectExecutionRequest) (*DirectExecutionResponse, error)
	// Ping is a simple health check
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// Sync syncs state between TEEs
	Sync(context.Context, *SyncRequest) (*SyncResponse, error)
	// Heartbeat sends and receives TEE attestation and status updates
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// GetPeers retrieves a list of attested peers in the region
	GetPeers(context.Context, *GetPeersRequest) (*GetPeersResponse, error)
	mustEmbedUnimplementedTeeMeshServer()
}

// UnimplementedTeeMeshServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTeeMeshServer struct{}

func (UnimplementedTeeMeshServer) Discover(context.Context, *DiscoveryRequest) (*DiscoveryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Discover not implemented")
}
func (UnimplementedTeeMeshServer) DirectExecute(context.Context, *DirectExecutionRequest) (*DirectExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DirectExecute not implemented")
}
func (UnimplementedTeeMeshServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedTeeMeshServer) Sync(context.Context, *SyncRequest) (*SyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedTeeMeshServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedTeeMeshServer) GetPeers(context.Context, *GetPeersRequest) (*GetPeersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeers not implemented")
}
func (UnimplementedTeeMeshServer) mustEmbedUnimplementedTeeMeshServer() {}
func (UnimplementedTeeMeshServer) testEmbeddedByValue()                 {}

// UnsafeTeeMeshServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TeeMeshServer will
// result in compilation errors.
type UnsafeTeeMeshServer interface {
	mustEmbedUnimplementedTeeMeshServer()
}

func RegisterTeeMeshServer(s grpc.ServiceRegistrar, srv TeeMeshServer) {
	// If the following call pancis, it indicates UnimplementedTeeMeshServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TeeMesh_ServiceDesc, srv)
}

func _TeeMesh_Discover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeeMeshServer).Discover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeeMesh_Discover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeeMeshServer).Discover(ctx, req.(*DiscoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeeMesh_DirectExecute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirectExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeeMeshServer).DirectExecute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeeMesh_DirectExecute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeeMeshServer).DirectExecute(ctx, req.(*DirectExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeeMesh_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeeMeshServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeeMesh_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeeMeshServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeeMesh_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeeMeshServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeeMesh_Sync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeeMeshServer).Sync(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeeMesh_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeeMeshServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeeMesh_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeeMeshServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeeMesh_GetPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeeMeshServer).GetPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeeMesh_GetPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeeMeshServer).GetPeers(ctx, req.(*GetPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TeeMesh_ServiceDesc is the grpc.ServiceDesc for TeeMesh service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TeeMesh_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TeeMesh",
	HandlerType: (*TeeMeshServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Discover",
			Handler:    _TeeMesh_Discover_Handler,
		},
		{
			MethodName: "DirectExecute",
			Handler:    _TeeMesh_DirectExecute_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _TeeMesh_Ping_Handler,
		},
		{
			MethodName: "Sync",
			Handler:    _TeeMesh_Sync_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _TeeMesh_Heartbeat_Handler,
		},
		{
			MethodName: "GetPeers",
			Handler:    _TeeMesh_GetPeers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tee_mesh.proto",
}
